/* ============================================================
   SALES OS operating layer. NOT the source of truth.

   This file used to declare itself the single source of truth, which is exactly how it
   drifted: it accumulated its own copies of prices, sample sizes and claim rules, and each
   copy aged independently until the app was telling reps not to sell bulk while the site
   took metric-ton orders with working checkout.

   Precedence, highest first:
     1. website/data.js                          wins on SKUs, availability and list price
     2. sales-playbook/03-proof-and-claim-discipline.md   wins on claim wording
     3. 00-index.md                              wins on branding and the live blocker
   This file layers the daily operating motion on top of those. When it disagrees with any
   of them, it is wrong.
   ============================================================ */
const DATA = {

  /* -------- Proof hierarchy (claim discipline) -------- */
  proofTiers: [
    { t:1, k:"proof-1", name:"Certified / Listed", ex:"OMRI Listed · Puro.earth certified" },
    { t:2, k:"proof-2", name:"Lab-tested", ex:"Control Labs, IBI test panel: H/C, surface area, heavy metals, NPK" },
    { t:3, k:"proof-3", name:"Field-research supported", ex:"Published USDA-ARS research on LA sugarcane bagasse biochar (third-party, not our product)" },
    { t:4, k:"proof-4", name:"Customer-reported (anecdotal)", ex:"Charley's Chicks litter/mortality observations" },
    { t:5, k:"proof-5", name:"Hypothesis / needs validation", ex:"$/ton CDR revenue, yield lift %, feed claims" },
  ],

  /* ============ 3. ICP SEGMENTS ============ */
  segments: [
    {
      id:"compost", group:"Ag / Hort", name:"Commercial Composters & Compost Yards", tag:"Biochar · trial → paid order",
      summary:"Compost producers whose economics are gated by TURNOVER TIME. Peer-reviewed research shows biochar accelerates the compost cycle — faster maturity means more batches/year on the same pad, higher throughput, and more revenue. This is our sharpest, highest-urgency wedge: we don't sell an amendment, we sell throughput.",
      coreProblem:"Long compost turnover time caps how many batches they can finish per year. Every day shaved off the cycle frees pad space and adds sellable volume — so cycle-time reduction converts directly into revenue.",
      valueProp:"Biochar-amended windrows reach the thermophilic phase faster, run hotter, and break down organic matter quicker — research reports ~10–30% shorter cycles (e.g. 10% biochar cut ~14 days; maturity 40→30 / 25→19 / 18→10 days across studies). Same pad, more turns, more tons sold, plus a premium biochar-enriched finished product.",
      firmo:"Municipal & merchant composters, organics recyclers, compost yards · pad/windrow-space constrained · sells finished compost by yd³/ton",
      titles:["Owner / GM","Compost Operations Manager","Site / Pad Manager","Purchasing"],
      econ:"Owner / GM", tech:"Compost operations manager", user:"Windrow / pad crew",
      pains:["Long turnover time caps annual throughput & revenue","Pad/space is the bottleneck — batches sit too long curing","Feedstock backs up faster than it cures","Odor, nitrogen loss, and inconsistent maturity","Wants to grow volume without buying more land"],
      triggers:["Capacity maxed / feedstock backlog","Expanding output without new pad space","Odor or compliance complaints","New offtake contract for finished compost","Peak-season throughput crunch"],
      urgency:["Backlogged feedstock right now","Season throughput crunch","Signed a finished-compost supply deal they can't keep up with"],
      disq:["No throughput/space constraint","Won't run a windrow trial","No way to measure days-to-maturity"],
      order:"Free sample + windrow trial → paid order against the 80 MT on hand (LOI locks Q4 supply/pricing as the fallback)", cycle:"3–8 weeks (one compost cycle proves it, then order/LOI)",
      proof:["Peer-reviewed cycle-time reduction (T3, general biochar)","Own side-by-side windrow A/B trial","Maturity + temperature + odor/N-loss data","Honeycomb pore structure = microbial habitat","Spec + OMRI"],
      objections:["Adds cost per yard","Need to see it in MY windrow","Dosing / how much per ton","Wood biochar cheaper"],
      offer:"Side-by-side windrow trial — biochar-amended vs control, measure days-to-maturity and peak temp", channel:"Direct call + site visit + windrow trial",
      tags:["seg:compost","persona:ops","zoneA","zoneB"],
      rank:{ speed:3, recurring:5, margin:4, carbon:5, strategic:5, freight:5, complexity:2 }
    },
    {
      id:"soilblend", group:"Ag / Hort", name:"Soil & Media Blenders", tag:"Biochar · supporting",
      summary:"Regional soil/media blenders that buy amendments in volume and resell engineered/premium blends. Best freight fit + fast reorder loop. Lead with moisture performance and a differentiated organic/carbon SKU (and cross-sell throughput to any who also compost).",
      coreProblem:"Blend quality and differentiation — sandy/premium mixes fail on water-holding, and they need an organic/carbon story to win engineered-soil bids without eroding margin.",
      valueProp:"Bagasse biochar screens clean into blends and holds ~3–3.5x its weight in water, firming up moisture performance in sandy and premium mixes, with inherent nutrients and an OMRI/carbon-negative story that lifts the blend's positioning.",
      firmo:"$2M–$50M rev · regional · buys by pallet/TL · owns blending + bagging",
      titles:["Owner / GM","Operations Manager","Purchasing / Buyer","Head Blender"],
      econ:"Owner / GM", tech:"Operations / Blend manager", user:"Yard crew",
      pains:["Inconsistent amendment quality","Water-holding complaints in sandy mixes","Margin pressure on premium blends","Customers asking for organic / carbon story","(If they compost feedstock) slow cure time caps supply"],
      triggers:["Launching a premium or organic line","Drought / water complaints","Losing bids on 'engineered' soils","Supplier quality miss"],
      urgency:["Spring build season","New retail contract","Competitor launched biochar blend"],
      disq:["No storage for bulk","Outside freight-viable zone w/ small volume","Won't trial"],
      order:"Free sample + pallet blend trial → paid order against inventory on hand (LOI reserves Q4 supply as the fallback)", cycle:"2–6 weeks",
      proof:["OMRI listing + IBI test-panel lab reports","Water-holding (3–3.5x) tech report","Spec sheet","Sample bag","Compost cycle-time data (if they cure feedstock)"],
      objections:["Wood biochar cheaper","Freight","Need proof it blends"],
      offer:"Free qualified sample + pallet trial w/ blend guidance", channel:"Direct call + field visit + email",
      tags:["seg:soilblend","persona:ops","zoneA"],
      rank:{ speed:3, recurring:5, margin:4, carbon:4, strategic:4, freight:5, complexity:2 }
    },
    {
      id:"agdist", group:"Ag / Hort", name:"Ag Input Distributors & Co-ops", tag:"Biochar · highest-leverage LOI",
      summary:"Distributors and farm co-ops that resell inputs to growers. THE highest-leverage LOI in the book — one distributor commitment represents many acres of Q4 volume, and unlocks B2B2C reach without our own field team. Seed with a free biochar sample now, reserve territory + pricing with an LOI.",
      firmo:"Regional/multi-branch · sells to growers · TL logistics in-house",
      titles:["Category / Product Manager","Purchasing Director","Branch Manager","Agronomy Lead"],
      econ:"Purchasing Director / Owner", tech:"Agronomy lead", user:"Grower customers",
      pains:["Need differentiated organic SKU","Grower demand for water/fertilizer efficiency","Thin margins on commodity inputs"],
      triggers:["Building organic/regenerative line","Grower requests","Carbon program participation"],
      urgency:["Pre-season stocking","Grant / cost-share programs","Competitor exclusivity threat"],
      disq:["Wants national exclusivity yr 1","No organic demand in region"],
      order:"Free sample + program preview → paid order against the 80 MT on hand + distributor LOI (reserves territory + Q4 volume)", cycle:"1–4 months",
      proof:["Published USDA-ARS field research","OMRI listing + lab reports","Distributor margin calc","Grower ROI calc"],
      objections:["Unproven demand","Margin","Support/marketing help"],
      offer:"Stocking pilot + co-branded grower trial program", channel:"Direct + trade assoc + referral",
      tags:["seg:agdist","persona:catman","zoneA","zoneB"],
      rank:{ speed:4, recurring:5, margin:4, carbon:5, strategic:5, freight:4, complexity:3 }
    },
    {
      id:"remediation", group:"Industrial", name:"Spill-Response & Environmental Remediation", tag:"Pellet/crumble beachhead · fastest sample→LOI (secondary track)",
      summary:"Contractors and enviro firms buying absorbents for spills, leachate, and industrial cleanup. The fastest absorbent sample→LOI cycle, but the SECONDARY track — biochar (80 MT on hand, ready now) is priority #1. Both forms carry live $275/MT super-sack SKUs, so a trial win on either converts to a paid order; only truckload volume waits on the Q4 ramp. Form follows the spill: pellets for confined work and thinner fluids (gas-side), crumble for large-area, high-volume cleanup (oil-side). Crumble-fit accounts must sit inside the tighter ~200mi freight ring. Absorbent pellets (up to ~5:1) beat wood (~2.5:1) on performance-per-dollar.",
      firmo:"Field service contractors · buys absorbents recurring · compliance-driven",
      titles:["Procurement Manager","Project Manager","Safety / EHS Manager","Warehouse Buyer"],
      econ:"Procurement / Ops Director", tech:"EHS / Project manager", user:"Field crews",
      pains:["Absorbent volume & disposal cost","Performance in the field","Sustainability reporting pressure"],
      triggers:["New contract / site","Poor absorbent performance","ESG mandate","Disaster season"],
      urgency:["Active spill / event","Bid response","Annual supply RFP"],
      disq:["Only wants viscous-spill sorbent","No recurring volume"],
      order:"Free sample + head-to-head demo → signed LOI (standing Q4 supply)", cycle:"3 weeks–3 months",
      proof:["5:1 vs 2.5:1 spec","Absorbency demo","Cost-per-gallon calc"],
      objections:["Already have absorbents","Need SDS/approvals","Disposal path"],
      offer:"Head-to-head absorbency demo + trial drum/pallet", channel:"Cold call + LinkedIn + demo",
      tags:["seg:remediation","persona:procurement","zoneA","zoneB","natl"],
      rank:{ speed:5, recurring:4, margin:4, carbon:2, strategic:4, freight:4, complexity:3 }
    },
    {
      id:"landscape", group:"Ag / Hort", name:"Landscape & Nursery Supply Yards", tag:"",
      summary:"Landscape supply and nursery/greenhouse distributors serving contractors and growers. Good pallet volume, premium positioning.",
      firmo:"Regional yards · contractor + retail traffic · seasonal",
      titles:["Buyer","Yard Manager","Owner"],
      econ:"Owner / Buyer", tech:"Yard manager", user:"Landscapers/growers",
      pains:["Differentiation vs big box","Water retention in installs","Organic demand"],
      triggers:["Premium line launch","Drought","Contractor requests"],
      urgency:["Spring season","New account"],
      disq:["No volume","Freight-negative"],
      order:"Free sample → signed LOI (Q4 supply)", cycle:"2–6 weeks",
      proof:["OMRI","Water-holding report","Retail bags","Sample"],
      objections:["Price","Turns/velocity","Merch support"],
      offer:"Retail-bag placement + sample", channel:"Field visit + call",
      tags:["seg:landscape","persona:landbuyer","zoneA","zoneB"],
      rank:{ speed:3, recurring:4, margin:4, carbon:3, strategic:3, freight:4, complexity:2 }
    },
    {
      id:"landfill", group:"Industrial", name:"Landfills & Municipal Public Works", tag:"",
      summary:"Waste operators and municipal public works for leachate control, spill kits, and storm cleanup. Larger, slower, contract-driven.",
      firmo:"Waste majors + municipalities · procurement/bid cycles",
      titles:["Operations Director","Procurement / Purchasing","Public Works Director","EHS"],
      econ:"Ops Director / Procurement", tech:"EHS", user:"Site crews",
      pains:["Leachate handling cost","Compliance","Sustainability optics"],
      triggers:["Leachate issue","RFP","Storm season","Sustainability mandate"],
      urgency:["Active compliance need","Budget cycle"],
      disq:["Bid locked to incumbent","No budget cycle window"],
      order:"Free sample + pilot → signed LOI (Q4 supply contract)", cycle:"2–6 months",
      proof:["Leachate absorbency","Certs","Case reference"],
      objections:["Procurement process","Incumbent","Disposal"],
      offer:"Pilot + bid/RFP response kit", channel:"RFP + direct + referral",
      tags:["seg:landfill","persona:opsdir","zoneA","zoneB","natl"],
      rank:{ speed:2, recurring:4, margin:3, carbon:2, strategic:4, freight:3, complexity:4 }
    },
    {
      id:"oilfield", group:"Industrial", name:"Oil & Gas Services", tag:"",
      summary:"Oilfield service companies for drilling/fracking fluid solidification and spill remediation. High volume, Gulf-dense, price + performance driven.",
      firmo:"OFS contractors · Gulf Coast dense · recurring consumables",
      titles:["Procurement Manager","Field Supervisor","HSE Manager"],
      econ:"Procurement / Ops", tech:"HSE / Field supervisor", user:"Rig/field crews",
      pains:["Fluid solidification cost","Disposal","HSE + ESG scrutiny"],
      triggers:["New job/site","Absorbent underperformance","ESG reporting"],
      urgency:["Active job","Supply RFP"],
      disq:["Viscous-only need","No recurring volume"],
      order:"Free sample + field demo → signed LOI (Q4 supply agreement)", cycle:"1–3 months",
      proof:["5:1 absorbency","Field demo","Cost calc"],
      offer:"Field trial + solidification demo", objections:["Incumbent","Approvals","Price"], channel:"Cold call + referral + demo",
      tags:["seg:oilfield","persona:procurement","zoneA","natl"],
      rank:{ speed:4, recurring:4, margin:4, carbon:2, strategic:4, freight:3, complexity:4 }
    },
    {
      id:"bedding", group:"Industrial", name:"Animal Bedding Distributors", tag:"",
      summary:"Bedding distributors for poultry/livestock. Absorbency + litter quality story. Feed/health claims gated behind regulatory review.",
      firmo:"Ag bedding distributors · recurring bulk · price-sensitive",
      titles:["Buyer","Owner","Barn / Operations Manager"],
      econ:"Owner / Buyer", tech:"Barn manager", user:"Growers/farmers",
      pains:["Litter moisture / ammonia","Bird comfort","Cost per house"],
      triggers:["Wet litter issues","New integrator spec","Cost pressure"],
      urgency:["Flock cycle","Seasonal moisture"],
      disq:["Wants unapproved feed claims from us","No volume"],
      order:"Free sample + house trial → signed LOI (Q4 supply)", cycle:"3–8 weeks",
      proof:["Absorbency spec","Charley's Chicks (anecdotal, flagged)"],
      objections:["Price vs shavings","Proof","Claims/regulatory"],
      offer:"House trial (bedding-only claims)", channel:"Direct + referral",
      tags:["seg:bedding","persona:opsdir","zoneA","zoneB"],
      rank:{ speed:3, recurring:4, margin:3, carbon:3, strategic:3, freight:4, complexity:3 }
    },
    {
      id:"cdr", group:"Carbon / ESG", name:"CDR / ESG Buyers & Brokers", tag:"PARKED · days 61–90",
      summary:"Corporate carbon-removal buyers, brokers, and marketplaces. PARKED for Month 1 — it needs verifiable deployed volume we don't yet have. Deployment (post-Q4 capacity) creates the credit supply they buy; open these conversations in days 61–90.",
      firmo:"Corporates w/ net-zero goals · brokers · CDR marketplaces",
      titles:["Head of Sustainability","Carbon/Climate Procurement","ESG Manager","Broker / Originator"],
      econ:"Sustainability / Procurement lead", tech:"MRV / carbon analyst", user:"ESG reporting team",
      pains:["Need durable, verifiable removal","Additionality & MRV rigor","Supply reliability"],
      triggers:["Annual carbon budget","Net-zero deadline","Puro/registry demand"],
      urgency:["Year-end procurement","Reporting cycle"],
      disq:["Wants credits with no deployment data","Sub-scale one-off"],
      order:"Forward purchase / offtake", cycle:"2–6 months",
      proof:["Puro.earth certified","H/C < 0.7 permanence","Deployment + MRV records"],
      objections:["Permanence/additionality","Volume reliability","Price"], offer:"Forward purchase tied to deployment pipeline", channel:"Warm intro + marketplace + broker",
      tags:["seg:cdr","persona:sustain","natl"],
      rank:{ speed:1, recurring:3, margin:5, carbon:5, strategic:5, freight:5, complexity:4 }
    },
  ],

  /* ============ 4. PERSONAS ============ */
  personas: [
    { id:"ops", name:"Compost / Blend Operations Manager", seg:"Composters & soil blenders",
      cares:"Throughput & turnover time, pad space, moisture performance, consistency, on-time freight",
      fears:"A new input that slows a batch, contaminates a windrow, or is inconsistent/late",
      needs:"A side-by-side windrow trial he can measure (days-to-maturity, peak temp), spec sheet, SDS",
      lang:"'turnover', 'windrow', 'cure time', 'yards', 'batch', 'maturity', 'pad space'",
      hates:"Carbon-credit jargon, vague eco pitches, no specs, claims he can't measure himself",
      disc:["What's your current compost turnover time, and what's the bottleneck — space or cure time?","How many batches/turns could you sell if the cycle were 2–4 weeks shorter?","Would you run a biochar-amended windrow next to a control so you can measure days-to-maturity yourself?"],
      open:"Research shows biochar can cut compost cycle time 10–30% — more batches per year on the same pad. Want to run one windrow with it against a control and measure the difference yourself?",
      cta:"Set up a side-by-side windrow trial + send the spec sheet" },
    { id:"catman", name:"Distributor Category Manager", seg:"Ag distribution",
      cares:"Sell-through, margin, differentiation, low support burden",
      fears:"Dead inventory, a SKU growers won't pull through",
      needs:"Proof of demand, margin math, grower-facing ROI, marketing support",
      lang:"'turns', 'sell-through', 'program', 'margin', 'grower'",
      hates:"Unproven products with no pull-through plan",
      disc:["What's driving your organic/regenerative SKU decisions?","Which growers are asking about water or carbon?","What margin and support do you need to stock a new line?"],
      open:"We're a Louisiana carbon-negative soil amendment, OMRI Listed and independently lab-tested, with published third-party USDA-ARS research on sugarcane bagasse biochar behind the category — want to see the distributor margin + grower ROI model?",
      cta:"Propose a stocking pilot + co-branded grower trial" },
    { id:"landbuyer", name:"Landscape Supply Buyer", seg:"Landscape/nursery",
      cares:"Velocity, premium margin, contractor demand, seasonal fit",
      fears:"Slow-moving pallets, price objections from contractors",
      needs:"Retail bags, water-retention proof, sample, merch",
      lang:"'installs', 'contractors', 'retail bag', 'season'",
      hates:"Bulk-only when he needs bagged, no merch support",
      disc:["What premium amendments move for you now?","Where do installs fail on water?","Bag or bulk for your traffic?"],
      open:"OMRI Listed biochar in retail bags that cuts watering on installs — want samples for the yard?",
      cta:"Place retail bags + sample" },
    { id:"procurement", name:"Industrial Procurement Manager", seg:"Remediation/oilfield",
      cares:"Cost-per-job, performance, SDS/approvals, reliable supply",
      fears:"An absorbent that underperforms mid-cleanup or fails compliance",
      needs:"SDS, absorbency proof (5:1), trial, disposal path",
      lang:"'sorbent', 'per drum', 'SDS', 'disposal', 'job'",
      hates:"Green pitches with no spec or SDS",
      disc:["What absorbent are you running and cost per job?","Where does it underperform?","What's needed to test a free sample on the next job — and to lock Q4 supply with an LOI if it wins?"],
      open:"Bagasse absorbent soaks up to ~5:1 vs ~2.5:1 for wood — fewer bags per spill. Want a free sample + a head-to-head demo?",
      cta:"Book absorbency demo + ship free sample; present LOI on a win" },
    { id:"opsdir", name:"Operations / EHS Director", seg:"Landfill/PW/bedding",
      cares:"Compliance, total cost, reliability, reporting optics",
      fears:"Compliance miss, procurement risk, disposal liability",
      needs:"Certs, SDS, pilot data, references",
      lang:"'compliance', 'leachate', 'RFP', 'budget cycle'",
      hates:"Vendors who don't understand procurement/bid process",
      disc:["Where's leachate/moisture costing you now?","What's your procurement/bid timeline?","What would a successful pilot need to show?"],
      open:"Plant-based absorbent for leachate/spill control with full specs and certs — want to scope a pilot for the next budget cycle?",
      cta:"Scope pilot + RFP response kit" },
    { id:"sustain", name:"Corporate Sustainability / CDR Buyer", seg:"Carbon/ESG",
      cares:"Durable, verifiable removal; MRV rigor; supply reliability",
      fears:"Buying credits that don't survive scrutiny; greenwash risk",
      needs:"Puro certification, permanence data, deployment + MRV records",
      lang:"'durability', 'MRV', 'additionality', 'tCO2e', 'registry'",
      hates:"Vague 'sustainable' claims, credits with no deployment evidence",
      disc:["What's your removal target and durability threshold?","Which registries/standards do you require?","Forward purchase or spot, and what volume?"],
      open:"Puro-certified biochar removal from Louisiana ag waste, with deployment-level MRV records — want to discuss a forward purchase tied to our deployment pipeline?",
      cta:"Share deployment pipeline + forward-purchase term sheet" },
  ],

  /* ============ 5. MESSAGING ============ */
  messaging: {
    splitRule:"TWO SEPARATE AVATARS — NEVER mix products in one pitch. Absorbent Pellets/Crumble and Biochar go to two completely different people with different pain, language, proof, and channel. An absorbent pitch never says 'biochar / soil / compost / OMRI / carbon.' A biochar pitch never says 'spill / absorbent / SDS-for-disposal / oilfield / leachate.' Every email, call, landing page, one-pager, and deck is SINGLE-PRODUCT. If a contact somehow fits both, run two separate threads.",
    tracks:[
      {
        id:"absorbent", product:"Absorbent Pellets & Crumble",
        audience:"Oil & Gas · Spill Response · Environmental Remediation · Landfill · Industrial EHS",
        avatar:"An HSE/EHS manager, field/ops supervisor, or procurement lead at an industrial or oilfield operation. They already buy clay or wood absorbents on a recurring, budgeted line. They think in bags-per-spill, disposal weight and cost, SDS, approvals, and job cost — NOT agronomy, soil, or carbon. They want proof it performs on a real cleanup and that it won't fail a compliance review.",
        positioning:"For industrial, oilfield, spill-response, and landfill teams, American BioCarbon Absorbent Pellets are a plant-based sugarcane-bagasse sorbent that holds up to ~5× its weight (vs ~2.5× for wood) — so crews open about half the bags and send lighter saturated waste to disposal, at a fraction of the cost-per-gallon of clay or cellulose.",
        oneLiner:"A plant-based industrial absorbent that holds up to ~5× its weight — half the bags, lighter disposal, ~$0.15/gal absorbed.",
        pitch30:"You're buying clay or wood absorbents that barely hold their own weight. Ours is a sugarcane-bagasse pellet that soaks up to ~5× its weight — about half the bags per spill and less saturated weight to disposal, which is billed by the pound. 100% organic, low-dust, fully spec'd. Want a free sample to run against what you use now on your next cleanup?",
        pitch90:"American BioCarbon makes an industrial absorbent from sugarcane bagasse at the Cora Texas mill in White Castle, LA. Bagasse has a naturally ordered, honeycomb pore structure, so carbonized and pelletized it draws in and holds up to ~5× its weight in non-viscous liquid — versus about 2.5× for wood pellets. On a real spill that means roughly half the bags to handle and less saturated weight going to disposal, and since disposal is billed by the pound, that's fewer pounds and fewer truckloads hauled. It's 100% organic biomass with no chemical additives, low dust, and renewable. A full spec sheet is on file for your procurement and EHS review. Easiest way to see it: a free sample to run head-to-head against your current absorbent on the next cleanup.",
        proof:["Up to ~5:1 absorption vs ~2.5:1 wood (product spec / lab)","Spec sheet on request","Cost-per-gal absorbed ~$0.15 vs ~$2.88 cellulose / ~$7.31 clay","100% organic bagasse, low dust, no additives","Fewer bags + lighter saturated disposal weight per spill"],
        neverSay:["biochar","soil / compost / windrow","OMRI / IBI / organic","carbon / CDR credits","water-holding / agronomy"]
      },
      {
        id:"biochar", product:"100% Biochar",
        audience:"MULTIPLE avatars — Distributors/Co-ops · Row-Crop & Specialty Farmers · Ranchers/Livestock · Poultry/Chicken farms · Compost/Soil Blenders · Nurseries/Greenhouses",
        avatar:"Biochar is the DYNAMIC product — one material, many different buyers, each with a different pain and a different lead benefit. Do NOT use a generic biochar pitch: pull the ONE benefit that matters to the buyer in front of you (water-holding for farmers, ammonia/odor for poultry & ranchers, cycle-time for composters, margin/differentiation for distributors, media performance for nurseries). Full per-avatar messaging, specs, benefit-by-mechanism, and industry comparisons live in the → Biochar Specs & Avatars tab. Common ground: they think in yards/blends/water-holding/OMRI/sell-through — NOT spills, SDS, or oilfield.",
        positioning:"For ag distributors, soil/compost blenders, and growers, American BioCarbon 100% Biochar is an OMRI Listed, independently lab-tested sugarcane-bagasse biochar whose ordered honeycomb pore structure holds ~3–3.5× its weight in water and carries inherent nutrients (~0.6-0.2-0.7 NPK + Ca/Mg) — a differentiated, carbon-negative SKU that improves water/nutrient retention and, per research, can shorten compost cycles ~10–30%.",
        oneLiner:"OMRI Listed sugarcane biochar that holds ~3–3.5× its weight in water and can shorten compost cycles ~10–30% — a differentiated, margin-accretive line.",
        pitch30:"Commodity amendments compete on price alone. Ours is an OMRI Listed, independently lab-tested bagasse biochar with an ordered honeycomb pore structure that holds ~3–3.5× its weight in water and carries inherent nutrients — so it firms up water-holding in sandy and premium blends and, per peer-reviewed research, can shorten compost cycles ~10–30%. Differentiated line, real supply story. Want a free sample to trial in one blend or windrow?",
        pitch90:"American BioCarbon makes a 100% sugarcane-bagasse biochar at the Cora Texas mill in White Castle, LA. Unlike most wood biochar, bagasse has a naturally ordered honeycomb pore structure that holds roughly 3–3.5× its weight in water, retains nutrients, and gives soil microbes protected habitat — and it carries inherent nutrients (~0.6-0.2-0.7 NPK plus Ca/Mg). It's OMRI Listed and independently lab-tested against the IBI test panel, measuring below IBI and EPA Class A heavy-metal thresholds. Published USDA-ARS research on sugarcane bagasse biochar supports the category (independent work, not a study of our product). For blenders it firms up moisture performance in sandy and premium mixes; for composters, peer-reviewed research shows biochar can shorten the cycle ~10–30% — more batches per year on the same pad. Best way to prove it is in your own operation: a free sample to run in one blend or a side-by-side windrow.",
        proof:["OMRI Listed · IBI tested","Holds ~3–3.5× its weight in water (technical report)","Inherent NPK ~0.6-0.2-0.7 + Ca/Mg","Published USDA-ARS bagasse field research (third-party)","Compost cycle ~10–30% shorter (peer-reviewed — validate in own windrow)","Heavy metals well below IBI / EPA Class A"],
        neverSay:["spill / cleanup","absorbent / sorbent / 5:1","SDS for disposal","oilfield / leachate / remediation","bags per spill"]
      }
    ],
    productPos:[
      { p:"Agricultural biochar", m:"Honeycomb bagasse structure → ~3–3.5x water-holding, inherent NPK + Ca/Mg, OMRI listed and IBI tested. A conditioner AND a nutrient-bearing matrix, not just black carbon." },
      { p:"Biochar-infused soil", m:"Ready-to-use blend — water retention, nutrient-holding, aeration with zero mixing. Drops into beds, pots, installs from the first watering." },
      { p:"Absorbent pellets", m:"5:1 absorption vs ~2.5:1 for wood — fewer bags per spill, lower disposal volume, plant-based and renewable. Spill, leachate, oilfield fluid, disaster." },
      { p:"Absorbent crumble", m:"Coarser form for fast, broad coverage on large-area / high-volume spills. Same 100% bagasse, spreads faster. Sellable now; oil-side and large-area fit; ~150-200mi freight ring." },
      { p:"Carbon removal credits", m:"Durable removal (H/C < 0.7), Puro-certified, generated by deploying the product. Sold as a layer on top of product movement — supply is our tons deployed." },
    ],
    comparisons:[
      { vs:"vs Wood biochar", win:"Ordered honeycomb pores → higher water-holding & nutrient retention; inherent nutrients; no trees cut" },
      { vs:"vs Synthetic fertilizer alone", win:"Reduces leaching, improves nutrient-use efficiency & water retention; complements — not replaces — fertility program" },
      { vs:"vs Compost alone", win:"Stable recalcitrant carbon (decades+), consistent lab-verified spec, adds durable structure compost can't" },
      { vs:"vs Wood/clay absorbents", win:"5:1 vs 2.5:1 absorbency; plant-based and renewable bagasse feedstock; lower disposal volume per gallon captured" },
      { vs:"vs Doing nothing", win:"Water/fertilizer efficiency, compliance & ESG story, differentiated resale SKU" },
      { vs:"vs Buying carbon credits w/o product", win:"Real deployed tons + MRV trail = defensible, durable removal — not paper offsets" },
    ],
    dualStory:"Simple version for buyers: You buy and use the product for its performance — water-holding, absorbency, soil health. Because our biochar locks carbon into a stable form for the long haul, the act of using it removes CO₂. That removal is independently certified (Puro.earth) and can be sold as a carbon credit. We handle the carbon side; you get a better product, often at better economics because the carbon layer subsidizes the price.",
    proofMap:[
      { claim:"Accelerates composting / shorter turnover time", rel:"Composters, soil blenders", src:"Peer-reviewed (general biochar)", tier:3, safe:"Research shows biochar can shorten the compost cycle ~10–30% and speed maturity — validate in your own windrow trial", risk:"'Our biochar cuts 14 days off your compost' (no VEJ-specific trial yet)" },
      { claim:"~3–3.5x water-holding capacity", rel:"Blenders, growers, landscape", src:"Lab-tested / American BioCarbon report", tier:2, safe:"Holds roughly 3–3.5x its weight in water (bagasse biochar, per technical report)", risk:"'Holds 5x water' as a blanket claim" },
      { claim:"5:1 absorption ratio", rel:"Remediation, oilfield, bedding", src:"Product spec / lab", tier:2, safe:"Up to ~5:1 absorption vs ~2.5:1 for wood pellets", risk:"'Absorbs any chemical' — specify non-viscous" },
      { claim:"OMRI Listed / IBI tested", rel:"Organic ag, distributors", src:"OMRI listing + Control Labs", tier:1, safe:"OMRI Listed, and independently lab-tested against the IBI test panel", risk:"'IBI Certified' in any form — we have NEVER held it. Also never 'USDA Organic' — no certification and no filed application." },
      { claim:"Puro.earth certified carbon", rel:"CDR/ESG buyers", src:"Certified", tier:1, safe:"Puro.earth certified carbon removal", risk:"Stating a fixed $/ton or tCO2e without confirmation" },
      { claim:"Low heavy metals", rel:"Organic, food-chain, compliance", src:"Lab (Control Labs IBI)", tier:2, safe:"Heavy metals 1–2 orders of magnitude below IBI/EPA Class A thresholds", risk:"'Zero contaminants'" },
      { claim:"Permanence / carbon-negative", rel:"CDR buyers", src:"Lab (H/C) + standard", tier:2, safe:"H/C molar ratio < 0.7 supports durable, long-term carbon retention", risk:"'Permanent forever' without standard reference" },
      { claim:"Yield / poultry health benefits", rel:"Growers, bedding", src:"Customer-reported / needs validation", tier:4, safe:"Customer-reported observations; not a formal performance or feed claim", risk:"Any feed/health claim as fact (AFIA/AAFCO/GRAS review required)" },
    ],
  },

  /* ============ 8. OUTREACH ============ */
  outreach:[
    { seg:"Soil Blenders", persona:"Ops Manager",
      steps:[
        { t:"Email 1 — Day 0", b:"Subject: bagasse biochar for your blends\n\nHi {First} — we make a 100% sugarcane bagasse biochar out of White Castle. It screens clean into soil blends and holds ~3x its weight in water, so it firms up moisture performance in sandy mixes. OMRI Listed, independently lab-tested.\n\nWorth a free sample bag to run in your premium blend? I'll include the spec + a quick blend guide.\n\n— {Me}, VEJ" },
        { t:"Call opener", b:"Hey {First}, {Me} with American BioCarbon down in White Castle — we turn sugarcane bagasse into biochar for soil blenders. Quick reason I called: folks running sandy or premium mixes use it to hold moisture and carry nutrients. What are you blending right now?" },
        { t:"Voicemail", b:"{First}, it's {Me} with American BioCarbon, {phone}. We make bagasse biochar for soil blends — holds about 3x its weight in water, screens clean. I'll send a spec by email; if it fits I'll drop you a free sample. Talk soon." },
        { t:"LinkedIn note", b:"Hi {First} — we make Louisiana bagasse biochar for soil blenders (OMRI Listed, independently lab-tested). Would love to send you a sample to trial in a blend. Open to it?" },
        { t:"Email 2 — Day 4 (value)", b:"Subject: the water-holding number\n\n{First} — quick proof: our bagasse biochar's honeycomb pore structure holds ~3–3.5x its weight in water (technical report attached), vs ~2x for typical wood biochar. That's the difference blenders feel in sandy mixes.\n\nWant a sample to test? Just need your best ship-to." },
        { t:"Email 3 — Day 9 (sample CTA)", b:"Subject: sample bag\n\n{First} — happy to ship a free qualified sample so you can run it in your own blend. If it performs, we scale to pallet then standing LTL. What blend would you test it in first?" },
        { t:"Breakup — Day 16", b:"Subject: close the loop\n\n{First} — I'll stop reaching out for now. If moisture performance or an organic/carbon-negative blend ever moves up your list, we're here and 300 miles away. I'll leave the spec attached." },
      ],
      nurture:"Monthly: seasonal blend tips, a customer proof point, or a new cert/data drop. No hard sell." },
    { seg:"Ag Distributors", persona:"Category Manager",
      steps:[
        { t:"Email 1 — Day 0", b:"Subject: carbon-negative organic SKU for your line\n\nHi {First} — American BioCarbon makes a Louisiana bagasse biochar (OMRI Listed, independently lab-tested, with published USDA-ARS field research behind the category). Distributors use it as a differentiated organic/regenerative SKU with a water + carbon story growers are asking for.\n\nCan I send the distributor margin model + grower ROI calc?" },
        { t:"Call opener", b:"Hi {First}, {Me} with American BioCarbon. We supply a bagasse biochar and I'm talking to distributors building out organic/regenerative lines. Are your growers asking about water efficiency or carbon yet?" },
        { t:"Voicemail", b:"{First}, {Me} with American BioCarbon, {phone}. Louisiana biochar, OMRI listed and independently lab-tested, with a distributor program and grower ROI model. Sending details by email — would value 15 minutes." },
        { t:"LinkedIn note", b:"Hi {First} — building a distributor program for our Louisiana bagasse biochar (OMRI listed, lab-tested, carbon-negative). Think it could differentiate your organic line. Open to a quick look at the margin model?" },
        { t:"Email 2 — Day 4", b:"Subject: the demand + margin question\n\n{First} — two things distributors ask: will it pull through, and what's the margin. On pull-through: it's OMRI-listed, with published USDA-ARS field research on bagasse biochar and a grower water/fertilizer-efficiency story. On margin: attached model shows a stocking pilot at [placeholder] with volume rebates. Worth a call?" },
        { t:"Email 3 — Day 9", b:"Subject: co-branded grower trial\n\n{First} — best way to de-risk: a stocking pilot plus a co-branded grower trial so your reps have a local proof point. I'll supply samples + trial docs. Which branches would you start with?" },
        { t:"Breakup — Day 16", b:"Subject: parking this\n\n{First} — I'll pause here. When an organic/carbon SKU moves up the priority list, the margin model and trial program are ready to go." },
      ],
      nurture:"Monthly: grower proof points, program economics, regional trial results, cost-share/grant angles." },
    { seg:"Remediation / Oilfield", persona:"Procurement Manager",
      steps:[
        { t:"Email 1 — Day 0", b:"Subject: 5:1 absorbent, fewer bags per job\n\nHi {First} — American BioCarbon makes a plant-based bagasse absorbent that soaks up ~5:1 vs ~2.5:1 for wood pellets. Fewer bags per spill, lower disposal volume, carbon-neutral. Full spec sheet available.\n\nWant a head-to-head absorbency demo or a trial pallet on your next job?" },
        { t:"Call opener", b:"Hi {First}, {Me} with American BioCarbon. We make a bagasse absorbent that outperforms wood 2-to-1 on soak-up. Reason I called — crews use fewer bags per spill and pay less on disposal. What absorbent are you running now?" },
        { t:"Voicemail", b:"{First}, {Me} with American BioCarbon, {phone}. Plant-based absorbent, 5:1 soak vs 2.5:1 for wood. I'll email the spec — happy to do a demo or trial pallet on your next job." },
        { t:"LinkedIn note", b:"Hi {First} — we make a 5:1 bagasse absorbent (vs 2.5:1 wood) for spill/fluid remediation. Can I send the spec sheet + set up a quick demo?" },
        { t:"Email 2 — Day 3", b:"Subject: cost per gallon captured\n\n{First} — the number that matters: at ~5:1, you capture the same spill with far fewer bags than wood or clay, so cost-per-gallon and disposal volume both drop. Attached: the spec sheet + a cost-per-gallon comparison. Want a trial pallet staged for the next job?" },
        { t:"Email 3 — Day 8", b:"Subject: trial pallet\n\n{First} — easiest path: we stage a trial pallet, your crew runs it head-to-head on the next spill, and you see the bag count difference live. What site should we ship to?" },
        { t:"Breakup — Day 15", b:"Subject: last note\n\n{First} — I'll stop here. When absorbent cost, disposal volume, or ESG reporting comes up, we're ready with specs and a trial pallet." },
      ],
      nurture:"Monthly: disposal-cost angles, ESG/HSE reporting value, disaster-season readiness." },
    { seg:"Landfill / Public Works", persona:"Ops / EHS Director",
      steps:[
        { t:"Email 1 — Day 0", b:"Subject: leachate & spill absorbent — pilot for next cycle\n\nHi {First} — American BioCarbon makes a plant-based bagasse absorbent (5:1) for leachate control and spill response, with full specs and certifications. Several ops teams pilot it to cut moisture-handling cost and strengthen sustainability reporting.\n\nCan I scope a pilot aligned to your budget cycle?" },
        { t:"Call opener", b:"Hi {First}, {Me} with American BioCarbon. We supply a plant-based absorbent for leachate and spill control with full specs. I'm reaching out to scope pilots for the next budget cycle — where does moisture or leachate cost you most right now?" },
        { t:"Voicemail", b:"{First}, {Me} with American BioCarbon, {phone}. Plant-based absorbent for leachate/spill, pilot-friendly. Emailing details — would like to understand your procurement timeline." },
        { t:"LinkedIn note", b:"Hi {First} — plant-based absorbent for leachate/spill control (specs, certs). Would like to scope a pilot for your next budget cycle. Open to a short call?" },
        { t:"Email 2 — Day 5", b:"Subject: what a pilot would show\n\n{First} — a clean pilot would measure absorbent volume used, moisture handled, and disposal impact vs your current material. I'll bring specs, certs, and a simple success scorecard. What's your RFP/budget timeline?" },
        { t:"Email 3 — Day 11", b:"Subject: RFP-ready kit\n\n{First} — if it's easier to route through procurement, I can send an RFP-ready kit (specs, certs, references). Who should receive it?" },
        { t:"Breakup — Day 18", b:"Subject: parking this\n\n{First} — I'll pause. When the budget window opens or leachate cost climbs, the pilot kit is ready." },
      ],
      nurture:"Quarterly: compliance updates, sustainability-reporting value, references." },
    { seg:"Animal Bedding", persona:"Buyer / Barn Manager",
      steps:[
        { t:"Email 1 — Day 0", b:"Subject: drier litter, fewer bags\n\nHi {First} — American BioCarbon makes a bagasse-based absorbent used for animal bedding. It soaks up several times its weight in moisture, which helps keep litter drier. Plant-based and renewable.\n\n(Bedding performance only — we don't make feed or health claims.) Want a house trial?" },
        { t:"Call opener", b:"Hi {First}, {Me} with American BioCarbon. We make a bagasse absorbent used as bedding — helps hold litter moisture. Where are you seeing wet-litter issues right now?" },
        { t:"Voicemail", b:"{First}, {Me} with American BioCarbon, {phone}. Bagasse-based bedding absorbent, holds moisture well, plant-based. I'll email details — open to a house trial." },
        { t:"LinkedIn note", b:"Hi {First} — bagasse-based bedding absorbent that holds litter moisture well. Can I send specs and set up a house trial?" },
        { t:"Email 2 — Day 5", b:"Subject: house trial\n\n{First} — simplest proof is a trial in one house: compare litter moisture and bag usage vs your current bedding. I'll ship a trial quantity. Which operation would you test first?" },
        { t:"Breakup — Day 12", b:"Subject: last note\n\n{First} — I'll stop here. If wet litter or bedding cost comes up, we're ready with specs and a trial." },
      ],
      nurture:"Seasonal: moisture-season readiness, bedding-cost angles. NEVER unapproved feed/health claims." },
    { seg:"CDR / ESG Buyers", persona:"Sustainability / Carbon Buyer",
      steps:[
        { t:"Email 1 — Day 0", b:"Subject: Puro-certified biochar removal, deployment-backed\n\nHi {First} — VEJ produces durable carbon removal via bagasse biochar (H/C < 0.7), Puro.earth certified, generated by real deployed tons in Louisiana ag/industrial use — with deployment-level MRV records.\n\nWould you be open to discussing a forward purchase tied to our deployment pipeline?" },
        { t:"Call opener", b:"Hi {First}, {Me} with American BioCarbon. We generate Puro-certified biochar carbon removal from deployed sugarcane bagasse biochar. What's your durability threshold and standard for removals this year?" },
        { t:"Voicemail", b:"{First}, {Me} with American BioCarbon, {phone}. Durable, Puro-certified biochar removal backed by real deployment and MRV. Sending details — would value a conversation on a forward purchase." },
        { t:"LinkedIn note", b:"Hi {First} — durable Puro-certified biochar removal, deployment + MRV backed. Open to discussing a forward purchase tied to our pipeline?" },
        { t:"Email 2 — Day 5", b:"Subject: why deployment-backed matters\n\n{First} — the differentiator: our credits come from physical tons actually deployed and documented, not paper offsets. That gives you defensible additionality + durability. I can share our MRV approach and deployment forecast. Useful?" },
        { t:"Email 3 — Day 12", b:"Subject: term sheet outline\n\n{First} — if there's fit, I'll send a forward-purchase outline sized to our conservative deployment pipeline (we never sell more credits than deployable tons). What volume and delivery window fits your program?" },
        { t:"Breakup — Day 20", b:"Subject: parking this\n\n{First} — I'll pause. When your removal budget cycle opens, our deployment-backed supply and MRV package are ready." },
      ],
      nurture:"Quarterly: deployment volume updates, MRV/registry progress, durability data." },
  ],

  /* ============ 9. COLLATERAL ============ */
  deck:[
    { s:"Title", p:"Frame identity fast", b:["American BioCarbon, biochar and absorbents from Louisiana sugarcane bagasse","Co-located at Cora Texas Sugar Mill, White Castle, LA"], cta:"—" },
    { s:"The waste-to-value story", p:"Origin + credibility", b:["Sugarcane bagasse: renewable ag byproduct, no trees cut","Oxygen-limited pyrolysis >500°C → stable biochar"], cta:"—" },
    { s:"Why bagasse beats wood", p:"Core differentiation", b:["Ordered honeycomb pore structure","~3–3.5x water-holding vs ~2x wood","Inherent NPK + Ca/Mg; 5:1 absorbency vs 2.5:1"], cta:"—" },
    { s:"Product family", p:"Show the range", b:["Bulk/bagged biochar","Biochar-infused soil","Absorbent pellets & crumble","Carbon removal credits"], cta:"—" },
    { s:"Proof & certifications", p:"De-risk", b:["OMRI Listed · IBI tested · Puro.earth certified","Published USDA-ARS field research (third-party)","Heavy metals well below IBI/EPA thresholds"], cta:"—" },
    { s:"The dual-value model", p:"The hook", b:["Every ton = product revenue + carbon-removal credit","We handle carbon; you get better product economics"], cta:"—" },
    { s:"Segment fit (tailor)", p:"Make it about them", b:["Blenders: moisture + organic SKU","Distributors: differentiated line + margin","Industrial: 5:1 absorbency + disposal savings"], cta:"—" },
    { s:"Economics / ROI", p:"Show the money", b:["Distributor margin model","Grower water/fertilizer efficiency","Cost-per-gallon captured (absorbent)"], cta:"Insert calculator output" },
    { s:"Proof it works", p:"Evidence", b:["Field study conclusions","Lab spec panels","Customer proof point (flagged if anecdotal)"], cta:"—" },
    { s:"How we start", p:"Lower the barrier", b:["Free sample (Pellets 1 lb / Biochar 8 oz)","Trial with agreed success criteria","If it wins → LOI locks Q4 supply, pricing & territory"], cta:"Book a free sample" },
    { s:"Logistics & terms", p:"Practicality", b:["Free samples now, 4–7 biz days from White Castle","Volume supply (bulk/bagged) from Q4","Q4 price band locked by LOI (placeholder until COGS set)"], cta:"—" },
    { s:"Next step", p:"Single clear CTA", b:["Approve a free sample / demo","Name the trial use case + success criteria","Sign an LOI on a win to reserve Q4 supply"], cta:"Ship sample this week" },
  ],
  onePagers:["Windrow trial protocol + data sheet (composter close)","Agricultural biochar","Biochar-infused soil","Absorbent pellets","Absorbent crumble","Distributor / reseller program","Industrial remediation","Carbon removal / CDR","Technical spec sheet","Organic / regulatory proof sheet","Comparison: vs wood biochar / wood pellets"],
  calculators:[
    { id:"distMargin", name:"Distributor Margin", inputs:["Your cost / unit","Resale price / unit","Units / month"], formula:"margin/unit = resale − cost; monthly profit = margin × units; margin % = margin/resale", saves:["est. product revenue","delivered margin"] },
    { id:"absorbent", name:"Absorbent Cost-per-Gallon", inputs:["Spill volume (gal)","Absorbent price / lb","Absorption ratio (lb liquid : lb sorbent)"], formula:"sorbent lb = spill_lb / ratio; cost = lb × price/lb; compare 5:1 vs 2.5:1", saves:["est. product revenue","competitor / status quo"] },
    { id:"blended", name:"Product + Carbon Blended Value", inputs:["Tons","Product margin / ton","tCO2e per ton (EST)","CDR $ / tCO2e (EST)"], formula:"product margin + (tons × tCO2e/ton × $/tCO2e) = blended value; carbon marked ESTIMATE", saves:["blended margin (incl. carbon)","est. CDR revenue"] },
    { id:"freight", name:"Freight-Aware Delivered Margin", inputs:["Product revenue","COGS","Freight cost"], formula:"delivered margin = revenue − COGS − freight; margin % = /revenue", saves:["delivered margin","est. freight"] },
  ],
  sample:{
    sizes:["Absorbent Pellets — 1 lb sample (free, S&H incl.)","Absorbent Crumble — 1 lb sample (free, S&H incl.)","100% Biochar — 8 oz sample (free, S&H incl.)","LIVE bulk: Biochar $450/MT · Pellets & Crumble $275/MT (1,650 lb super sacks)","(Q4+) truckload supply once capacity is online"],
    gates:["Confirmed ICP + use case","Named decision-maker (who can sign an LOI)","Agreed success criteria","Ship-to address"],
    fields:["account","contact","product","sample size","use case","success criteria","ship-to","ship date","carrier/tracking","follow-up date","outcome"],
    follow:["Day 0 ship confirmation","Day 3 'arrived?'","Day 7 trial check-in","Day 10 results + present LOI"],
    success:"Buyer confirms the sample met the pre-agreed metric (moisture, absorbency, blend behavior) → present the LOI to lock Q4 supply.",
  },
  windrowTrial:{
    goal:"Prove — in the composter's own operation — that biochar-amended windrows reach maturity faster and run hotter than their control, converting a Tier-3 general research claim into THEIR OWN measured data. This trial IS the close: shorter cycle = more batches/year on the same pad.",
    design:"Split one uniform feedstock batch into two matched windrows built the same day from the same pile: CONTROL (their normal recipe) and TREATMENT (same recipe + biochar). Keep everything else identical — size, turning schedule, location, moisture target. One variable: the biochar.",
    doses:[
      { r:"5% by volume", use:"Conservative / cost-sensitive start", note:"Often enough to see faster heat-up" },
      { r:"10% by volume", use:"Research 'sweet spot' — most cited acceleration", note:"Recommended default treatment rate" },
      { r:"15–20% by volume", use:"Aggressive / high-N or wet feedstock", note:"Also boosts finished-product biochar value" },
    ],
    steps:[
      "Pick one homogeneous feedstock batch; record recipe, C:N if known, start moisture.",
      "Build 2 matched windrows same day, same dimensions, from the same pile.",
      "Add biochar to TREATMENT at chosen dose (default 10% v/v); blend evenly. Control gets none.",
      "Log Day 0 baseline: temp, moisture, weight/volume, ambient temp.",
      "Turn both on the SAME schedule; never turn one without the other.",
      "Record temperature daily (3-probe avg per windrow), moisture 2–3x/week.",
      "Track days in thermophilic range (>55°C / 131°F) and peak temp for each.",
      "Call maturity when temp stabilizes near ambient after turning + passes their normal maturity check.",
      "Log DAYS-TO-MATURITY for both. The gap is the headline number.",
      "Optional: odor observations, N-loss proxy, finished screening/quality notes.",
    ],
    measure:[
      { m:"Days to maturity", why:"THE headline — drives batches/year & revenue", how:"Days from build to passing their maturity check" },
      { m:"Days to thermophilic (>55°C)", why:"Faster heat-up = faster process", how:"Days until sustained >55°C / 131°F" },
      { m:"Peak temperature", why:"Hotter = more microbial activity & pathogen kill", how:"Highest 3-probe avg" },
      { m:"Time held >55°C", why:"Pathogen/weed-seed kill compliance", how:"Count of days in range" },
      { m:"Moisture stability", why:"Confirms it's process speed, not drying", how:"% moisture 2–3x/week" },
      { m:"Odor (optional)", why:"Site/compliance value-add", how:"1–5 subjective scale at turns" },
    ],
    dataCols:["Day","Date","Control temp (°F)","Treatment temp (°F)","Control moisture %","Treatment moisture %","Turned? (Y/N)","Notes"],
    success:"Treatment reaches maturity meaningfully sooner than control (target ≥10% fewer days) at equal or better maturity/quality. Even 3–5 days per cycle compounds into multiple extra batches per year.",
    roiBridge:"Convert days saved → batches/year → revenue: (current cycle days ÷ new cycle days − 1) = % more throughput on the same pad. Feed the numbers into the Distributor/Throughput calculator and present alongside the LOI — the ROI is what justifies committing Q4 volume.",
    guardrails:[
      "One variable only — if they change turning, moisture, or recipe, the trial is invalid.",
      "Don't promise a specific day-count up front. The trial produces THEIR number (Tier-3 → their own data).",
      "Match windrow size & schedule exactly or the comparison is noise.",
      "Get maturity defined THEIR way before Day 0 so results are undisputable.",
    ],
    deliverable:"1-page trial protocol + printable daily data-capture sheet, co-branded, left on-site at the discovery visit. Closing artifact = filled sheet + a one-line ROI (days saved × batches/year).",
  },

  objections:[
    { o:"Biochar is too expensive", mean:"Doesn't see ROI yet", resp:"Reframe on outcome: water/fertilizer efficiency or fewer absorbent bags + disposal savings. Carbon layer can subsidize price.", proof:"ROI calc + field study", next:"What's your current cost per [unit/job]?", disq:"No budget & no use case" },
    { o:"I already use compost", mean:"Sees overlap", resp:"Complement, not replacement — biochar adds stable carbon + water-holding compost can't; use together.", proof:"Comparison sheet", next:"Where does your compost fall short on moisture/structure?", disq:"—" },
    { o:"Wood biochar is cheaper", mean:"Price-anchored", resp:"Performance-per-dollar: ordered honeycomb pores → higher water-holding + inherent nutrients; ask them to trial side-by-side.", proof:"American BioCarbon comparison / SEM", next:"Want a head-to-head sample?", disq:"—" },
    { o:"I don't understand carbon credits", mean:"Confused / skeptical", resp:"Keep it simple: buy the product for performance; we handle carbon; it may improve your price. No action needed from them.", proof:"Dual-value one-pager", next:"Want the plain-English version?", disq:"—" },
    { o:"Freight kills the economics", mean:"Delivered cost fear", resp:"Freight-zone pricing; concentrate volume; carbon value + product margin defend delivered cost inside zone.", proof:"Freight-aware calc", next:"What volume/frequency could you commit?", disq:"Zone C + tiny volume" },
    { o:"We need proof it works", mean:"Risk-averse", resp:"That's exactly what the trial is for — define success up front, ship a sample, measure.", proof:"Field study + sample", next:"What would prove it to you?", disq:"Won't define success" },
    { o:"We need organic certification", mean:"Compliance gate", resp:"OMRI Listed today. We are NOT USDA Organic certified and have no filed application — never imply otherwise. Provide the OMRI listing + IBI test-panel lab reports.", proof:"Cert docs", next:"Is OMRI sufficient for your program?", disq:"—" },
    { o:"We need specs / SDS", mean:"Procurement gate", resp:"Send the spec sheet immediately; it's a buying signal. If they specifically require an SDS, escalate - we do not have one yet.", proof:"Spec sheet", next:"Who else needs to see these?", disq:"—" },
    { o:"We need a trial first", mean:"Ready-ish", resp:"Great — qualify, set success criteria, ship. Trial is the path forward.", proof:"Sample workflow", next:"What use case + success metric?", disq:"—" },
    { o:"We need net terms", mean:"Cash-flow", resp:"Net-15 pilot → Net-30 established (placeholder policy). Tie to volume/reorder.", proof:"Terms sheet", next:"What terms does procurement require?", disq:"—" },
    { o:"We already have absorbents", mean:"Incumbent", resp:"Not rip-and-replace — trial pallet on one job, measure bag count + disposal vs incumbent.", proof:"Cost-per-gallon calc", next:"Trial on the next spill?", disq:"—" },
    { o:"Need regulatory approval (feed/animal)", mean:"Compliance risk", resp:"Agree — we sell bedding/absorbency only; feed/health claims require AFIA/AAFCO/GRAS review. Stay in-bounds.", proof:"Bedding spec (no feed claims)", next:"Bedding-only trial works?", disq:"Insists on unapproved claims" },
    { o:"New supplier is risky", mean:"Reliability fear", resp:"Start small (sample→pallet), show consistency via lab batch data, scale on proof.", proof:"Batch lab consistency", next:"Start with a low-risk pallet?", disq:"—" },
  ],

  /* ============ 11. PLAYBOOK ============ */
  playbook:{
    principles:["Sample first, then convert a winning trial to a PAID metric-ton order at the published site price","A PO against the roughly 80 MT on hand is the Month-1 win. The LOI sits on top of it to reserve Q4 TRUCKLOAD volume","Never advance a stage without its exit criteria","Every trial has a written success metric before it ships","Claim discipline: match every claim to its proof tier","Multi-thread any account worth a meaningful recurring order","Carbon is a days-61–90 layer, not the Month-1 pitch","Log it in the app or it didn't happen"],
    qual:{ framework:"MEDDIC-A (adapted): Metrics, Economic buyer, Decision criteria, Decision process, Identify pain, Champion + Application/Carbon fit",
      criteria:["Real, specific use case","Order potential ≥ pallet w/ recurring path","Freight fit (zone A/B or volume justifies C)","Named decision-maker engaged","Urgency / trigger present","Proof requirements known","Sample success criteria agreed","Carbon-credit eligibility assessed","Operational complexity acceptable"] },
    discovery:{
      groups:[
        { g:"Business problem", q:["What outcome are you trying to fix (moisture, absorbency, differentiation, compliance)?","What does that problem cost you today?"] },
        { g:"Current solution", q:["What are you using now and who supplies it?","What's the gripe with it?"] },
        { g:"Economics", q:["What's your current cost per unit / job / house?","What would a win be worth?"] },
        { g:"Operations", q:["How do you handle/store/apply it?","Bulk or bagged — what fits your ops?"] },
        { g:"Technical", q:["What specs/SDS/certs does your process require?","Any particle size / moisture constraints?"] },
        { g:"Compliance / certs", q:["Do you need OMRI/organic or specific SDS?","Any regulatory gates (feed, disposal)?"] },
        { g:"Procurement", q:["Who signs off and what's the process?","Terms / MOQ requirements?"] },
        { g:"Logistics / freight", q:["Where's ship-to and what volume/frequency?","In-house TL or need delivered?"] },
        { g:"Trial / sample", q:["What would prove it to you?","What metric = success?"] },
        { g:"Carbon / ESG", q:["Any sustainability/ESG reporting pressure?","Interested in the carbon story or product-only?"] },
      ],
    },
    proofDemo:["Product education (bagasse → product story)","Spec sheet review","Use-case match to their problem","Ship free sample","Run trial vs agreed success metric","Document before/after (claim-safe)","Present the LOI to lock Q4 supply"],
    proposal:{ need:["qualified use case","estimated Q4 volume","decision maker who can sign","sample success criteria met","Q4 price band set"], structure:["Recap of their problem","Recommended product","Sample result / proof","LOI terms: committed volume + locked Q4 price + territory","Signature step (non-binding until Q4)"], },
    close:["Written LOI-close plan w/ dates","Confirm the signer + what their bar is","Present the LOI; adjust volume/territory as needed","On signature: log committed volume to the funding book; nurture toward Q4 offtake"],
    handoff:["Order details + delivery schedule","Application / usage guidance","MRV data capture (application, GPS/site, weights)","Success check-in scheduled","Reorder date set"],
    expansion:["Reorder reminders on cycle","Usage check-ins","Volume expansion / new-SKU cross-sell","Case study request","Referral ask"],
  },

  /* ============ 11b. CUSTOMER ONBOARDING (accounts) ============
     The admin/accounting spine under the sample→win→PO motion. Two doc flows:
     what WE send a new account (we're the vendor/payee) and what WE collect
     from them before we can invoice or extend terms. Owners map to whoBadge. */
  onboarding:{
    intro:"How a biochar buyer becomes a paying account on the books. The sales motion (sample → trial win → PO/LOI) rides on top of an administrative spine: the moment a trial wins, Accounting stands the customer up as a real account BEFORE the first invoice ships. Get the paperwork done in the win window and the first PO invoices clean; skip it and the first order stalls in the customer's AP department.",
    ownerNote:"Sales (Jesse) owns the relationship and hands off a won trial. Admin/Accounting (Victor) owns the packet, tax status, credit, and invoicing. Ops (Daniel) owns the physical shipment + compliance docs.",
    journey:[
      { stage:"1 · Qualified account", trigger:"Account passes MEDDIC-A qual", owner:"Jesse", admin:"Nothing yet — this is pure sales. Capture ship-to region + use case in the app so freight zone is known early.", exit:"Named buyer + real use case logged" },
      { stage:"2 · Sample request", trigger:"Buyer agrees to test a free sample", owner:"Jesse", admin:"Collect a lightweight New Account intake: company legal name, ship-to address, AP/buyer contact, product + use case. No credit or tax step yet — samples are free.", exit:"Intake captured, sample queued" },
      { stage:"3 · Sample shipped + trial", trigger:"Sample ships against agreed success metric", owner:"Daniel", admin:"Ship the COA with the sample. Log tracking. Trial runs against the written success metric.", exit:"Trial underway, metric agreed" },
      { stage:"4 · Trial win / intent", trigger:"Sample beats their current product; buyer signals intent to order", owner:"Jesse", admin:"⚡ HANDOFF TRIGGER. Sales notifies Accounting to open the onboarding packet. This is the window — do the admin now, while intent is hot.", exit:"Handoff logged; packet opened" },
      { stage:"5 · Account setup (admin gate)", trigger:"Onboarding packet sent + returned", owner:"Victor", admin:"The accounting/administrative gate — see the two doc flows below. We send our W-9; we collect their tax/resale status, credit app (if they want terms), and bill-to/ship-to. NOTHING invoices until tax status is resolved.", exit:"W-9 exchanged · tax status set · terms or prepay decided · account created in books" },
      { stage:"6 · First PO / order", trigger:"Signed quote or customer PO received", owner:"Victor", admin:"Convert quote → sales order. First order is prepay (CC/ACH) unless credit was approved in step 5. Confirm price, volume, freight terms (FOB), delivery date.", exit:"Order confirmed + payment method set" },
      { stage:"7 · Fulfillment & delivery", trigger:"Order released to ship", owner:"Daniel", admin:"Ship against PO. The COA travels with the load. Capture MRV data at delivery (application, GPS/site, weights) — the link to carbon revenue.", exit:"Delivered + MRV captured" },
      { stage:"8 · Invoice & payment", trigger:"Goods delivered", owner:"Victor", admin:"Invoice per terms. Apply sales tax UNLESS a valid exemption/resale cert is on file. Reconcile payment (prepay clears before ship, or Net-30 clock starts at delivery).", exit:"Invoiced + payment received/scheduled" },
      { stage:"9 · Reorder / account mgmt", trigger:"Delivery success confirmed", owner:"Jesse", admin:"Now a known account — reorders skip steps 1–5. Set reorder cadence, watch credit limit, refresh resale cert annually (most states expire).", exit:"Reorder date set; account recurring" },
    ],
    // What WE send the customer (ABC is the seller / payee / vendor)
    docsOut:[
      { doc:"ABC W-9", what:"Our completed IRS W-9 (legal name, EIN, address). Their AP needs it to set us up as a vendor — routine even though product sales usually aren't 1099-reportable.", when:"Step 5, on request", owner:"Victor" },
      { doc:"Quote / price sheet", what:"Written quote: SKU, price, volume, freight terms (FOB origin/destination), payment terms, validity date.", when:"Step 4–5", owner:"Jesse" },
      { doc:"Certificate of Analysis (COA)", what:"Lab spec for the batch — carbon %, moisture, particle size, pH. Required by ag/technical buyers.", when:"Ships with sample + every load", owner:"Daniel" },
      { doc:"Safety Data Sheet (SDS)", what:"Product safety/handling sheet. Many buyers can't receive material without it on file.", when:"Ships with sample + on setup", owner:"Daniel" },
      { doc:"Remittance / ACH details", what:"Our banking + remit-to instructions so they can pay by ACH/check.", when:"Step 5–6", owner:"Victor" },
      { doc:"Cert package (as needed)", what:"OMRI/organic or other compliance proof where the buyer's process requires it.", when:"On request", owner:"Victor" },
    ],
    // What WE collect from the customer before invoicing / extending terms
    docsIn:[
      { doc:"New-account / vendor form", what:"Their standard vendor-setup form or our intake: legal entity, bill-to, ship-to, AP contact, phone/email.", req:"Required", when:"Step 2 (lite) → 5 (full)", owner:"Victor" },
      { doc:"Resale / sales-tax exemption cert", what:"If they resell or are ag-exempt. MUST be on file to invoice tax-free — state-specific (LA, MS, AL, TX, FL). No cert = we charge sales tax.", req:"Required if claiming exemption", when:"Step 5 — before first invoice", owner:"Victor" },
      { doc:"Customer W-9 / tax ID", what:"Their W-9 or tax ID for our vendor/customer master and 1099 handling where applicable.", req:"Recommended", when:"Step 5", owner:"Victor" },
      { doc:"Credit application", what:"Only if they want Net-30 terms: entity info, trade references, bank ref, credit authorization. Otherwise first order is prepay.", req:"Required for terms", when:"Step 5", owner:"Victor" },
      { doc:"Signed quote or Purchase Order", what:"Their PO or a counter-signed quote — the order authorization we invoice against.", req:"Required", when:"Step 6", owner:"Jesse" },
      { doc:"Signed LOI (Q4 volume)", what:"For committed Q4 supply — non-binding volume/price/territory reservation. Separate from a spot PO.", req:"For offtake track", when:"Parallel", owner:"Jesse" },
    ],
    accounting:[
      "First order = PREPAY (CC or ACH) by default. Net-30 terms only after a credit app is approved.",
      "Sales tax: charge it UNLESS a valid resale/exemption certificate is on file. Ag/soil buyers are often exempt but the cert must be collected first — verify per state (LA, MS, AL, TX, FL).",
      "We send our W-9 to their AP; we collect their resale cert + (for terms) a credit app. Two-way, don't confuse the directions.",
      "Freight terms stated on every quote: FOB origin (buyer pays/arranges freight) vs delivered. Ties to the freight-zone model.",
      "One system of record: create the account in the books (QuickBooks/Shopify) at step 5 so the first invoice isn't the first data entry.",
      "Resale certs expire in most states — flag for annual refresh on recurring accounts.",
    ],
    // Setup tasks: build the reusable onboarding packet ONCE (persistent checks)
    setup:[
      "Draft ABC W-9 (final EIN + legal name) as a ready-to-send PDF|done",
      "Build the New-Account / customer intake form (legal name, bill-to, ship-to, AP contact, tax status)",
      "Assemble resale/exemption-cert guidance for each Gulf South state (LA, MS, AL, TX, FL)",
      "Create a simple credit application (entity, trade refs, bank ref, authorization) for Net-30 requests",
      "Write the standard quote template (SKU, price, volume, FOB freight terms, payment terms, validity)",
      "Confirm COA + SDS are current and packaged to ship with every sample and load",
      "Set the default payment policy: first order prepay, terms only after credit approval",
      "Stand up the customer master in the books (QuickBooks/Shopify) with tax + terms fields",
      "Create the sales→accounting handoff trigger in the app (fires at trial-win / step 4)",
    ],
    // Repeatable per-account checklist Accounting runs each time (defaults OFF)
    perAccount:[
      "New-account intake captured (legal name, bill-to, ship-to, AP contact)",
      "Sent our W-9 to their AP",
      "Tax status resolved — resale/exemption cert collected OR sales tax will apply",
      "Terms decided — prepay confirmed OR credit app approved for Net-30",
      "Signed quote or customer PO received",
      "Account created in the books with tax + terms fields set",
      "COA + SDS delivered / on file with the customer",
      "First invoice issued against the PO",
      "Reorder cadence + resale-cert refresh date set",
    ],
    faq:[
      { q:"Do customers send us a W-9?", a:"It's the other way for payment — WE send THEM our W-9 so their AP can set us up as a vendor. We may collect their W-9/tax ID for our own customer master, but the one that unblocks their payment is ours going out." },
      { q:"When do we collect the resale/tax cert?", a:"At account setup (step 5), before the first invoice. Without a valid cert on file we must charge sales tax — so collect it during the trial-win window, not after invoicing." },
      { q:"Can a new customer buy on Net-30?", a:"Not on the first order. First order is prepay (CC/ACH). Net-30 opens only after they submit and we approve a credit application." },
      { q:"What triggers onboarding?", a:"A trial win with buying intent (step 4). Sales hands off to Accounting, who opens the packet while intent is hot. Don't wait for the PO to start the paperwork." },
    ],
  },

  /* ============ 15. FINAL CHECKLIST ============ */
  checklist:{
    biochar:["Confirm the 80 MT of finished biochar is packaged, QC'd & ship-ready","Set biochar bulk price + minimum order qty by freight zone (internal)","Get freight/LTL quotes from White Castle for the top biochar zones","Stand up a biochar bulk-order / PO path (Shopify or manual invoice)","Sample→order SOP: on a winning trial, quote from the 80 MT within 24h","Track MT sold vs 80 MT on the dashboard"],
    website:["✅ Temporary website build-out complete (localhost + combined-site)|done","Victor reviews & approves site copy + both product tracks","Create 2 sample SKUs in Shopify (Pellets 1 lb, Biochar 8 oz)","Wire Shopify variant IDs into the site sample forms","Publish certs/spec sheets to the site (SDS / OMRI listing / IBI-panel lab reports / Puro)","Install/stage approved site in Shopify → publish over current site","Sample + reserve-supply forms route to Jesse + Victor + Daniel (tested end-to-end)"],
    build:["CRM objects + fields (Account/Contact/Deal/Sample/LOI/Activity)","Sample→LOI funnel: statuses + sample tracker","Dashboards (samples shipped, sample→LOI, committed volume)","Target account list view (both tracks, freight-zoned)"],
    collateral:["Absorbent 1-pager (industrial — single-product)","Biochar 1-pager (ag — single-product)","Sample-kit insert + test protocol","Spec sheets + SDS (from Victor)","Comparison: pellets vs wood/clay · biochar vs wood biochar","Product photos (real close-ups + facility)"],
    lists:["150–200 accounts across BOTH product ICPs (Gulf South + freight-viable)","Contacts + verified emails (Apollo)","ICP-tagged + freight-zoned; shared with Victor"],
    firstActions:["Free-sample outreach ONLY in the cold touch (the sample is the door-opener; the order comes after a trial win)","BIOCHAR track (PRIORITY): distributor/blender/composter/grower emails + calls","Absorbent track (secondary): EHS/spill/oilfield emails + calls","Ship free samples within 48h of qualification (biochar first)","Convert winning trials on any line to paid metric-ton POs (biochar ships against the 80 MT on hand)","Book discovery/technical calls (Victor takes technical)"],
  },

  /* ============ 14. BIOCHAR — SPECS, DATA & AVATARS ============
     Biochar is the DYNAMIC product: one material, many buyers. Absorbent pellets & crumble = one industrial avatar;
     biochar sells across ag distribution, row-crop farmers, ranchers/livestock, poultry (bedding + in-feed),
     compost/blenders, and nursery/greenhouse — each with a different benefit that matters to THEM.
     Pull the spec + the ONE comparison + the ONE benefit that fits the avatar in front of you. */
  biochar:{
    intro:"100% sugarcane-bagasse biochar from the Cora Texas mill (White Castle, LA). Oxygen-limited pyrolysis >500°C turns a renewable ag byproduct — no trees cut — into a stable, nutrient-bearing carbon. Its defining edge vs most biochar is the bagasse feedstock's naturally ordered honeycomb pore structure, which drives higher water-holding, nutrient retention, and microbial habitat than random-pore wood char.",
    spec:[
      ["Feedstock","100% sugarcane bagasse (renewable byproduct; no trees)"],
      ["Production","Oxygen-limited pyrolysis >500°C"],
      ["Pore structure","Ordered honeycomb (vs random/fractured wood char)"],
      ["Organic carbon","~58–65% (dry basis)"],
      ["Water-holding","~3–3.5× its weight (per technical report)"],
      ["Inherent nutrients","NPK ~0.6-0.2-0.7 + Ca & Mg (most wood char has ~none)"],
      ["H/C molar ratio","<0.7 → durable, long-term carbon"],
      ["Heavy metals","1–2 orders of magnitude BELOW IBI & EPA Class A thresholds"],
      ["Bulk density","~80–320 kg/m³ (low density → full-truckload discipline, 1-MT bags)"],
      ["Certifications","OMRI Listed · Puro.earth carbon pathway. Independently lab-tested against IBI test-panel thresholds (NOT IBI certified). No USDA Organic."],
      ["Carbon permanence","Stores carbon 200+ yrs (Puro methodology)"],
      ["CDR yield","~1.5–2.5 tCO2e per ton biochar (1.9 base case) — days-61–90 layer"],
    ],
    benefits:[
      { mech:"Water-holding", b:"Honeycomb pores hold ~3–3.5× their weight in water — drought resilience, fewer irrigation passes, real lift in sandy/degraded soils.", who:"Farmers · ranchers · blenders · nurseries", tier:2 },
      { mech:"Nutrient retention (CEC)", b:"Holds nutrients in the root zone → less leaching, better nutrient-use efficiency; complements (doesn't replace) the fertility program.", who:"Farmers · distributors", tier:2 },
      { mech:"Inherent nutrients", b:"Carries its own NPK (~0.6-0.2-0.7) + Ca/Mg — unlike most wood biochar, which is inert carbon only.", who:"Farmers · growers", tier:2 },
      { mech:"Microbial habitat", b:"Protected pore space houses soil microbes → healthier biology and rhizosphere.", who:"Farmers · ranchers · growers", tier:3 },
      { mech:"pH / liming", b:"Raises pH in acidic soils, improving nutrient availability.", who:"Farmers · ranchers", tier:3 },
      { mech:"Compost acceleration", b:"Peer-reviewed research: biochar can shorten the compost cycle ~10–30%, raise pile temperature, and cut nitrogen loss — more batches per year on the same pad.", who:"Compost yards · blenders", tier:3 },
      { mech:"Ammonia / odor binding", b:"UGA + composting studies show biochars lower ammonia and retain nitrogen in litter/manure — drier litter, less odor, better air quality.", who:"Poultry · ranchers · dairy", tier:3 },
      { mech:"Carbon permanence", b:"Durable carbon (H/C <0.7), Puro-certified pathway → a genuine carbon-negative story and a future CDR revenue layer (days 61–90).", who:"Distributors · ESG-minded buyers", tier:2 },
      { mech:"Poultry in-feed (GATED)", b:"Research shows FCR and body-weight gains at 0.5–1% inclusion and manure ammonia reduction — BUT feed claims are AAFCO/FDA-CVM gated. Frame as bedding/environmental until cleared.", who:"Poultry integrators · feed mills", tier:4 },
    ],
    comparisons:[
      { h:"Bagasse biochar vs Wood biochar", cols:["","Bagasse (ours)","Wood biochar"], rows:[
        ["Pore structure","Ordered honeycomb","Random / fractured"],
        ["Water-holding","~3–3.5×","~2×"],
        ["Inherent nutrients","Yes (NPK + Ca/Mg)","Minimal"],
        ["Best for","Sandy/degraded soils, compost, blends","Structural amendment only"],
      ]},
      { h:"Biochar vs Compost (use together)", cols:["","Biochar","Compost"], rows:[
        ["Carbon stability","Decades–centuries (recalcitrant)","Weeks–months (labile)"],
        ["Spec consistency","Lab-verified, consistent","Variable batch to batch"],
        ["Adds","Durable structure + water/nutrient holding","Biology + immediate organic matter"],
        ["Verdict","Complements compost — not a substitute","Pair for best result"],
      ]},
      { h:"Biochar vs Synthetic fertilizer alone", cols:["","With biochar","Fertilizer alone"], rows:[
        ["Leaching","Reduced (nutrients held in root zone)","Higher losses"],
        ["Nutrient-use efficiency","Improved","Baseline"],
        ["Water retention","Improved","None"],
        ["Role","Complements the fertility program","—"],
      ]},
      { h:"Poultry in-feed — research signals (GATED, do not claim)", cols:["Study","Rate","Reported effect"], rows:[
        ["Broiler 2021","3%","Worse starter, better grower-finisher FCR + full-cycle gain"],
        ["Broiler 2020","2–4%","Up to ~17% manure ammonia reduction; worse perf at higher dose"],
        ["Broiler 2025","1%","+ up to 4.7% body-weight gain; − up to 6.7% FCR"],
        ["Aflatoxin challenge","0.5%","Restored body weight vs aflatoxin-only control"],
        ["Commercial base case","0.5–1.0%","Cleanest market-sizing band (mixed results higher)"],
      ]},
      { h:"Market / cost positioning ($/ton)", cols:["","American BioCarbon bulk","Market"], rows:[
        ["List price","$450 / metric ton (live on the site, working checkout)","Wholesale $600 to $2,778; modal ~$1,600"],
        ["Quoting status","BLOCKED: freight and COGS unverified, so no firm biochar price goes out beyond the published $450/MT. The older $700/ton figure was an internal modeling placeholder and is superseded.",""],
        ["CA study","—","$600–$1,300 avg (20–40% bulk discounts)"],
        ["Angle","Enter low, undercut premium retail","Carbon layer can further subsidize price"],
      ]},
    ],
    avatars:[
      { name:"Ag Input Distributors & Co-ops", who:"Category / purchasing manager reselling inputs to growers", pain:"Need a differentiated, margin-accretive organic SKU their growers actually pull through", angle:"A carbon-negative, OMRI listed and lab-tested biochar with a real supply story + distributor margin — one line that differentiates the shelf", lead:"OMRI listing + IBI-panel lab reports + published USDA-ARS research + distributor margin model", sample:"Sample + program preview to evaluate with their team", claim:"" },
      { name:"Row-Crop & Specialty Growers (Farmers)", who:"Farmer / agronomy lead on sandy, drought-prone, or degraded ground", pain:"Water and fertilizer cost; yield variability on poor soils", angle:"Holds ~3–3.5× its weight in water and keeps nutrients in the root zone — more efficient water + fertilizer, better resilience", lead:"Water-holding report + NUE + published USDA-ARS field research (third-party)", sample:"Sample for a controlled strip/plot trial", claim:"Frame yield as trial-measured; no blanket yield guarantees" },
      { name:"Ranchers / Livestock & Pasture", who:"Rancher / land manager running pasture + livestock", pain:"Pasture productivity, soil water-holding, and manure/odor management", angle:"Improves pasture soil water + nutrient retention, and binds ammonia/odor in manure and high-traffic areas", lead:"Water-holding + ammonia/odor studies + soil health", sample:"Sample for a pasture soil or manure/bedding area trial", claim:"Environmental/soil framing; no animal-health claims" },
      { name:"Poultry / Chicken Farms", who:"Broiler/layer grower, barn manager, or integrator", pain:"Wet litter, ammonia, air quality, bird comfort — and feed efficiency (integrators)", angle:"TWO uses: (1) BEDDING/LITTER now — drier litter, lower ammonia, better air (claim-safe); (2) IN-FEED later — research shows FCR/gain + ammonia benefits at 0.5–1% (regulatory-gated)", lead:"Ammonia-reduction studies (bedding) · in-feed research pack (gated)", sample:"House trial on litter moisture/ammonia (bedding-only claims)", claim:"BEDDING/ABSORBENCY ONLY until AAFCO/FDA-CVM feed pathway clears. NO feed/health claims." },
      { name:"Compost Yards & Soil Blenders", who:"Owner/operator whose throughput is capped by cure time, or a blender needing differentiation", pain:"Turnover time caps batches/year; commodity blends compete on price", angle:"Shortens the compost cycle ~10–30% (more batches, same pad) and upgrades blends' water-holding + organic/carbon story", lead:"Compost cycle-time research + water-holding + windrow trial protocol", sample:"Bulk sample for a side-by-side windrow or blend trial", claim:"Cycle-time is Tier-3 general research — validate in THEIR windrow" },
      { name:"Nurseries / Greenhouses / Landscape", who:"Head grower, yard buyer, or landscape supplier", pain:"Media water-retention, premium differentiation, contractor/retail demand for organic", angle:"Biochar-based media component improves water retention and root-zone performance; premium, OMRI-listed, carbon-negative positioning", lead:"OMRI + water-holding + retail-bag option", sample:"Sample for a controlled media/grow trial", claim:"Media-property framing" },
    ],
    guardrails:[
      "One material, MANY avatars — lead with the ONE benefit that matters to the buyer in front of you, not the whole list.",
      "Never say IBI Certified (we have never held it) or USDA Organic (no certification, no filed application). Say OMRI Listed, and IBI tested for the lab work.",
      "Poultry IN-FEED and any feed/health claim is AAFCO/FDA-CVM gated — until cleared, sell poultry as BEDDING/environmental only.",
      "Compost cycle-time and yield lifts are Tier-3 general-biochar research → present as 'validate in your own trial,' never as a product-specific guarantee.",
      "Carbon/CDR is a days-61–90 layer — mention as upside, don't lead ag pitches with it.",
    ],
  },
};
