/* ============================================================
   American BioCarbon, B2B site rebuild · source of truth
   Copy reviewed by "The Offer Architect": every section must
   increase desire, increase trust, or move toward conversion.
   Claim discipline enforced (see CLAIMS).
   ============================================================ */

const CDN = "https://cdn.shopify.com/s/files/1/0773/9270/7876/files/";
const ASSETS = {
  logoColor:  CDN+"abc-logo-horiz_color.png?v=1710167731",
  logoRev:    CDN+"abc-logo-horiz_rev_38e8f78a-b79f-4c53-8b36-d10683e943cf.webp?v=1710182358",
  pelletsMock:CDN+"AbsorbentPelletsMock.jpg?v=1699280021",
  pelletsPhoto:CDN+"AmericanBiocarbon2021-292.jpg?v=1699280021",
  biocharMock:CDN+"100BiocharMock.jpg?v=1699279980",
  biocharPhoto:CDN+"AmericanBiocarbonBiochar1.jpg?v=1699279980",
  biocharLg:  CDN+"biochar-lg.jpg?v=1702141148",
  hands:      CDN+"hands.webp?v=1686923164",
  /* high-res wide hero photos (1920×801 native, master ≥3840), from the live site carousel */
  heroPellets:CDN+"Hero_Options_2.png?v=1710183682&width=2560",
  heroBiochar:CDN+"Hero_Options_3_04d3fb95-6d64-443f-8885-f6c4071bdcfe.png?v=1710183785&width=2560",
  heroCrumble:CDN+"Hero_Options_4.png?v=1710183683&width=2560",
  heroBiosoil:CDN+"Hero_Options_5.png?v=1710183683&width=2560",
  heroBagasse:CDN+"Hero_Options_1.png?v=1710183683&width=2560",
  icCert:     CDN+"values.svg?v=1710184994",
  icLeaf:     CDN+"leaf.svg?v=1710185049",
  icTech:     CDN+"tech.svg?v=1710185049",
};

const BRAND = {
  name:"American BioCarbon",
  legal:"American BioCarbon · ProGreaux LLC",
  address:"32525 Highway 1 South, White Castle, LA 70788",
  location:"White Castle, Louisiana · co-located with the Cora Texas Sugar Mill",
  phone:"(add phone)",           // TODO: confirm
  email:"sales@americanbiocarbon.com", // TODO: confirm
};

/* Primary + secondary CTAs used across the site */
const CTA = {
  sample:  { label:"Request quote",         href:"#/request-sample" },
  freeSamplePellets: { label:"Free Sample", href:"#/shop/absorbent-pellets" },
  freeSampleBiochar: { label:"Free Sample", href:"#/shop/agricultural-biochar" },
  quote:   { label:"Talk to us about volume",       href:"#/request-quote" },
  spec:    { label:"Get spec sheet",           href:"#/request-docs?doc=spec" },
  specDownload: { label:"Download Spec Sheet",      href:"#/request-quote" },
  sds:     { label:"Download SDS",                  href:"#/request-docs?doc=sds" },
  docs:    { label:"Request Technical Package",     href:"#/request-docs" },
  specialist:{ label:"Talk to a Remediation Specialist", href:"#/contact" },
  distributor:{ label:"Reserve Distributor Territory", href:"#/request-quote?type=distributor" },
  biochar: { label:"Request a Free Biochar Sample", href:"#/request-sample?type=biochar" },
  carbon:  { label:"Request Carbon Removal Info",   href:"#/contact?type=carbon" },
};

/* Top navigation */
const NAV = [
  { label:"Absorbents", children:[
    { label:"Absorbent Pellets", href:"#/product/absorbent-pellets" },
    { label:"Absorbent Crumble", href:"#/product/absorbent-crumble" },
  ]},
  { label:"Industries", children:[
    { label:"Oil & Gas", href:"#/industry/oil-gas" },
    { label:"Industrial Remediation", href:"#/industry/industrial-remediation" },
    { label:"Environmental Remediation", href:"#/environmental-remediation-solutions" },
    { label:"Spill Response", href:"#/industry/spill-response" },
    { label:"Landfill Leachate", href:"#/industry/landfill-leachate" },
    { label:"Distributors & Resellers", href:"#/distributors-resellers-industries" },
  ]},
  { label:"Agriculture", children:[
    { label:"100% Biochar", href:"#/product/agricultural-biochar" },
    { label:"Biochar-Infused Soil", href:"#/product/biochar-infused-soil" },
    { label:"Soil Blenders & Compost", href:"#/industry/soil-blenders" },
    { label:"Distributors & Resellers", href:"#/distributors-resellers-agriculture" },
  ]},
  { label:"Carbon Removal", href:"#/product/carbon-removal" },
  { label:"Buy Online", href:"#/buy" },
  { label:"Technical Data", href:"#/technical" },
  { label:"About", href:"#/about" },
];

/* Proof band (verify exact language before publishing, see CLAIMS) */
const PROOF = {
  items:[
    { icon:ASSETS.icCert, title:"Third-Party Certified", sub:"OMRI Listed · IBI Certified · Puro.earth" },
    { icon:ASSETS.icLeaf, title:"Carbon-Negative", sub:"Durable carbon storage from ag byproduct" },
    { icon:ASSETS.icTech, title:"Patented Process", sub:"Bagasse separation & controlled pyrolysis" },
  ],
  microRow:["Up to 5:1 absorption","Plant-based & renewable","Bulk · bulk-bag · truckload","SDS & spec on request"],
  certs:[
    { name:"OMRI Listed", status:"verified", note:"Organic input listing, confirm current listing ID" },
    { name:"IBI Certified", note:"Int'l Biochar Initiative program", status:"verified" },
    { name:"Puro.earth Certified", status:"verified", note:"CORC carbon-removal pathway" },
    { name:"Independent lab analyses", status:"lab", note:"Heavy metals well below IBI / EPA Class A thresholds" },
    { name:"USDA-ARS field study", status:"field", note:"Multi-year sugarcane bagasse biochar study" },
    { name:"USDA Organic", status:"pending", note:"PENDING, never present as certified" },
  ],
};

/* ============ TECHNICAL DATA / RESOURCES (gated) ============ */
/* Documents are NOT freely downloadable. Every item is delivered
   only after a documentation request (email + qualifying info). */
const TECH = {
  // Certification & compliance, shown as proof, no file exposed
  compliance:[
    { item:"OMRI Listed", scope:"Organic input listing (soil amendment)", status:"verified" },
    { item:"IBI Certified", scope:"Int'l Biochar Initiative program", status:"verified" },
    { item:"Puro.earth Certified", scope:"CORC carbon-removal methodology", status:"verified" },
    { item:"Independent lab analysis", scope:"Heavy metals below IBI / EPA Class A thresholds", status:"lab" },
    { item:"USDA-ARS field study", scope:"Multi-year sugarcane bagasse biochar trials", status:"field" },
    { item:"USDA Organic", scope:"Certification in progress", status:"pending" },
  ],
  // Document catalog, the gated deliverables (spec sheets first for primary products)
  docs:[
    { id:"abs-spec", name:"Absorbent Pellets & Crumble, Spec Sheet", cat:"Absorbents", desc:"Absorbency ratio, bulk density, granulation, form factors.", primary:true },
    { id:"bio-spec", name:"100% Biochar, Spec Sheet", cat:"Agriculture", desc:"Organic carbon, water-holding, NPK, particle size.", primary:true },
    { id:"abs-sds", name:"Absorbent Pellets & Crumble, SDS", cat:"Absorbents", desc:"Safety data sheet for handling, storage, and disposal." },
    { id:"abs-disposal", name:"Saturated-Material Disposal Guidance", cat:"Absorbents", desc:"Handling and disposal profile for spent absorbent." },
    { id:"bio-lab", name:"Independent Lab Analysis, Heavy Metals & Nutrients", cat:"Agriculture", desc:"Full IBI panel: metals vs thresholds, NPK, H/C ratio, surface area." },
    { id:"omri-cert", name:"OMRI / IBI Certificates", cat:"Certification", desc:"Current listing documentation." },
    { id:"carbon-mrv", name:"Carbon Removal, Methodology & MRV Summary", cat:"Carbon", desc:"Puro.earth pathway, permanence (H/C), and MRV approach." },
    { id:"studies", name:"Peer-Reviewed Research Package", cat:"Research", desc:"Curated studies on bagasse biochar and biochar in composting." },
  ],
  // Peer-reviewed & field research (citations public; full package gated)
  studies:[
    { title:"Multi-Year Field Application of Sugarcane Bagasse Biochar", authors:"Lima, White & Webber, USDA-ARS", venue:"US Biochar Initiative Conference, 2019", type:"field",
      finding:"Multi-year Louisiana field trials evaluating bagasse and cane-trash biochar effects on sugarcane and soil.", note:"Specific to sugarcane bagasse biochar.", url:"https://www.usda.gov" },
    { title:"Biochar addition reduces nitrogen loss and accelerates the composting process", authors:"Bioresource Technology", venue:"Elsevier, 2021", type:"peer",
      finding:"Biochar shortened the composting cycle and reduced nitrogen loss by shifting the core microbial community.", note:"General biochar research.", url:"https://doi.org/10.1016/j.biortech.2021" },
    { title:"Enhancing composting efficiency using biochar amendments", authors:"Scientific Reports", venue:"Nature, 2025", type:"peer",
      finding:"Biochar raised pile temperature and accelerated maturation while cutting greenhouse-gas emissions.", note:"General biochar research.", url:"https://doi.org/10.1038/s41598-025" },
    { title:"Biochar's effect in the composting mechanism: a review", authors:"Bioresource Technology", venue:"Elsevier, 2023", type:"peer",
      finding:"Review: biochar shortens time to thermophilic phase, raises peak temperature, and speeds organic-matter degradation.", note:"General biochar research.", url:"https://doi.org/10.1016/j.biortech.2023" },
    { title:"ProGreaux Bagasse Biochar, IBI Laboratory Analyses", authors:"Control Laboratories", venue:"IBI Certification Program", type:"lab",
      finding:"Independent IBI panels: organic carbon 58 to 65%, H/C < 0.7, surface area ~230 to 260 m²/g, heavy metals well below thresholds.", note:"Product-specific lab data.", url:"https://www.biocharinitiative.org" },
  ],
  // Which documents matter to each industry (all gated)
  byIndustry:{
    "oil-gas":["abs-spec","abs-sds","abs-disposal"],
    "industrial-remediation":["abs-spec","abs-sds","abs-disposal"],
    "environmental-remediation":["abs-spec","abs-sds","abs-disposal"],
    "spill-response":["abs-spec","abs-sds"],
    "landfill-leachate":["abs-spec","abs-sds","abs-disposal"],
    "distributors":["bio-spec","bio-lab","omri-cert"],
    "soil-blenders":["bio-spec","bio-lab","omri-cert","studies"],
  },
  gateNote:"Spec sheets, SDS, lab analyses, and the research package are provided on request. Submit your details and we'll email the documents relevant to your application.",
  // Product-accurate certification sets (absorbents don't carry organic listings)
  certSets:{
    absorbents:[
      { item:"100% organic biomass", scope:"Sugarcane bagasse, no chemical additives", status:"verified" },
      { item:"Independent lab analysis", scope:"Composition & heavy-metal screening", status:"lab" },
      { item:"Safety Data Sheet (SDS)", scope:"Handling, storage & disposal", status:"verified" },
    ],
    biochar:[
      { item:"OMRI Listed", scope:"Organic input listing", status:"verified" },
      { item:"IBI Certified", scope:"Int'l Biochar Initiative program", status:"verified" },
      { item:"Independent lab analysis", scope:"Heavy metals below IBI / EPA Class A", status:"lab" },
      { item:"USDA-ARS field study", scope:"Sugarcane bagasse biochar trials", status:"field" },
      { item:"USDA Organic", scope:"Certification in progress", status:"pending" },
    ],
    carbon:[
      { item:"Puro.earth Certified", scope:"CORC carbon-removal methodology", status:"verified" },
      { item:"Lab-verified permanence", scope:"H/C molar ratio < 0.7", status:"lab" },
      { item:"MRV documentation", scope:"Deployment-based measurement & reporting", status:"verified" },
    ],
  },
  byProduct:{
    "absorbent-pellets":["abs-spec","abs-sds","abs-disposal"],
    "absorbent-crumble":["abs-spec","abs-sds","abs-disposal"],
    "agricultural-biochar":["bio-spec","bio-lab","omri-cert"],
    "biochar-infused-soil":["bio-spec","omri-cert"],
    "carbon-removal":["carbon-mrv","bio-lab"],
  },
};

/* ============ HOME (11 sections) ============ */
const HOME = {
  seo:{ title:"Plant-Based Industrial Absorbent & Bagasse Biochar | American BioCarbon",
    desc:"A plant-based industrial absorbent that holds up to 5× its weight in liquid, fewer bags, lighter disposal. Request a free sample; reserve volume supply for our Q4 capacity ramp. Bagasse biochar & carbon removal.",
    slug:"/", keyword:"plant-based industrial absorbent", schema:"Organization + WebSite" },
  heroOptions:[
    "Fewer bags per spill. Less weight to disposal.",
    "A plant-based absorbent that holds up to 5× its weight, vs ~2.5× for wood.",
    "Industrial absorbent, engineered from sugarcane. Absorbs more, disposes lighter.",
    "Solidify fluids and clean spills with a fraction of the bags.",
    "Renewable absorbents and biochar, built for industrial scale.",
  ],
  hero:{
    chosen:"Fewer bags per spill. Less weight to disposal.",
    sub:"Our sugarcane-bagasse absorbents, available as pellets, crumble, and fiber, hold up to 5× their weight in liquid, so crews open fewer bags and send fewer truckloads to disposal. Engineered for oilfield fluids, spill response, and industrial remediation.",
    primary:CTA.freeSamplePellets, secondary:CTA.quote,
    proofLine:["Up to 5× weight absorption","SDS & spec sheet available"],
    image:ASSETS.pelletsPhoto,
    /* Full-bleed cinematic carousel, each slide pairs a massive edge-to-edge
       photo with its own product-matched hero statement. */
    slides:[
      { label:"Absorbent Pellets", img:ASSETS.heroPellets, pos:"50% 62%", zoom:1.24, origin:"50% 82%",
        h:"Fewer bags per spill.<br>Less weight to disposal.",
        sub:"Sugarcane bagasse absorbent pellets hold up to 5× their weight in liquid, so crews open fewer bags and haul fewer truckloads to disposal.",
        primary:CTA.freeSamplePellets, secondary:CTA.quote },
      { label:"100% Biochar", img:ASSETS.hands, pos:"50% 50%", zoom:1.06, origin:"50% 55%",
        h:"Carbon that stays<br>in the ground.",
        sub:"OMRI listed bagasse biochar builds soil, holds water and nutrients, and locks durable carbon away for centuries.",
        primary:CTA.freeSampleBiochar, secondary:CTA.quote },
      { label:"Absorbent Crumble", img:ASSETS.pelletsPhoto, pos:"50% 58%", zoom:1.1, origin:"50% 72%",
        h:"Cover more ground,<br>in less time.",
        sub:"A coarser grade that spreads fast across wide area, high volume spills, with the same high capacity bagasse absorption.",
        primary:CTA.freeSamplePellets, secondary:CTA.specDownload, specProduct:"absorbent-pellets" },
      { label:"BioSoil", img:ASSETS.heroBiosoil, pos:"50% 50%", zoom:1.05, origin:"50% 50%",
        h:"Peat-moss performance,<br>locally sourced.",
        sub:"Blended for peat-moss performance: 40% multipurpose fiber, 40% biochar, 20% coffee chaff—retains water and nutrients like peat moss with inherent NPK, zero mixing, no mined bog. Locally sourced. Coming Q4.",
        primary:CTA.biochar, secondary:CTA.quote },
    ],
  },
  offer:{
    kicker:"Test It On Your Terms",
    h:"Run it against your current sorbent, before you switch a thing",
    body:"Tell us the job and we'll ship an industrial sample kit with the SDS and spec sheet. Put it head-to-head with the wood or clay you use today, count the bags, weigh the disposal. If it earns the switch, we scale you to bulk, bulk-bag, or truckload supply on freight-aware pricing.",
    steps:[
      { n:"01", t:"Request a sample", d:"Give us the fluid, site, and volume. Samples ship in 4 to 7 business days with SDS + spec." },
      { n:"02", t:"Test it head-to-head", d:"Run it beside your current absorbent on a real job." },
      { n:"03", t:"Scale on the numbers", d:"Fewer bags and lighter disposal earn the bulk contract." },
    ],
    primary:CTA.sample, secondary:CTA.quote,
  },
  problem:{
    h:"Standard absorbents make you buy, handle, and dispose of more than you should",
    body:"Wood and clay sorbents typically hold about 2.5× their weight or less. So you open more bags per spill, your crew handles more material, and you haul more truckloads to disposal, where you pay by the ton. Procurement needs three things at once: field performance, dependable supply, and documentation. Most absorbents deliver one.",
    points:[
      "More bags per job = more labor and more truck space",
      "More saturated weight = more disposal truckloads = more cost",
      "Dust and non-renewable waste add handling and ESG friction",
      "Hard to get specs, SDS, and a real bulk quote quickly",
    ],
  },
  buy:{
    kicker:"Buy Online · Samples & Bulk",
    h:"Order samples. Request bulk quotes.",
    sub:"Order a sample, run the head-to-head in your own operation, then scale to a freight-aware bulk-bag or truckload contract. Checkout is secured by Shopify.",
    trust:["Samples ship in 4 to 7 business days","OMRI-listed biochar","SDS & spec sheets on every SKU","US freight-aware bulk pricing","Checkout secured by Shopify"],
    steps:[
      { n:"01", t:"Order a sample or request a quote", d:"Buy a sample SKU online, or request a freight-aware bulk quote." },
      { n:"02", t:"Evaluate on your terms", d:"Review the spec sheet + SDS and run your own head-to-head test." },
      { n:"03", t:"Scale to a contract", d:"Move to a bulk-bag or truckload supply agreement on freight-aware pricing." },
    ],
    // cartPermalink stays empty until Victor/Jesse create the sample SKUs in Shopify;
    // when empty, "Order Sample" falls back to the sample request form.
    products:[
      // cartPermalink = Shopify cart deep-link (checkout engine). Format: https://<store-domain>/cart/<variantId>:1
      // NOTE: variant IDs below are the CURRENT live Shopify SKUs (Pellets 20 lb, Biochar 8 qt) used so checkout works
      // end-to-end today. Swap to the 1 lb / 8 oz SAMPLE variant IDs the moment Victor/Jesse create those SKUs.
      { id:"absorbent-pellets", name:"Absorbent Pellets", avail:"live", cat:"Absorbents", category:"Industrial Absorbent · Spill Control", accent:"aqua",
        claim:"A 5:1 absorption ratio means crews open fewer bags per spill and send lighter loads to disposal.",
        uses:["Drilling and frac fluid solidification","Oil and non-viscous chemical spill cleanup","Landfill leachate and aqueous waste","Animal bedding and pet litter"],
        chips:["1 lb sample bag","100% bagasse","Low dust"], unit:"1 lb Sample Bag", sampleWeight:"1 LB", photo:ASSETS.pelletsPhoto, free:true, truckloadQ4:true,
        bag:{ banner:"ABSORBENT PELLETS", iconSet:"absorbent",
          icons:["Natural Biomass","Agricultural Waste","Naturally Absorbent Fibers","Superior Liquid Retention"],
          uses:"Spill Cleanup (Oil, Solvents & Non-Viscous Chemicals) | Animal Bedding | Landfill Leachate Control | Oil & Gas Fluid Remediation (Drilling & Fracking) | Flood & Natural Disaster Cleanup",
          desc:"A carbon-neutral, plant-based absorbent made from sugarcane bagasse. These pellets soak up five times their own weight in liquid, outperforming standard wood pellets, and are just as easy to use: sprinkle over the mess, let them fully absorb, then sweep up and dispose. Renewable, sustainably sourced, and built for tough industrial and household jobs alike.",
          ingredients:"ANAEROBIC FERMENTED MICROTREATED BAGASSE", omri:false },
        desc:"Super-absorbent multi-purpose bagasse pellets made from the fiber left over when sugar is processed. A 5:1 absorption ratio suits spill cleanup, waste solidification, and remediation, as well as animal bedding and litter. Odorless, renewable, low dust, and easy to use.",
        gallery:[ CDN+"AbsorbentPelletsMock.jpg?v=1699280021", CDN+"AmericanBiocarbon2021-292.jpg?v=1699280021", CDN+"ABCAbsorbentPelletsFinal_printready.pdf.png?v=1699280021", CDN+"ABCAbsorbentPelletsFinal_printready.pdf_2.png?v=1699280021" ],
        sections:[
          { h:"Spill cleanup and remediation", body:"Soak up soil runoff, solvents, drilling and frac fluids, and other non-viscous liquids. Sprinkle the pellets over the spill, wait for full absorption, then sweep up and dispose of the saturated material per your local requirements." },
          { h:"Waste solidification", body:"A 5:1 absorption ratio solidifies aqueous and oilfield waste with less sorbent mass, so crews open fewer bags and send lighter loads to disposal." },
          { h:"Animal bedding", body:"Use as bedding by adding about a half gallon of water to the bag for wet bedding, or scatter the pellets across the habitat floor for dry bedding." },
          { h:"Pet litter", body:"A renewable, low-dust alternative to traditional litter for cats, rabbits, ferrets, birds, and more." },
        ],
        img:ASSETS.pelletsMock, variantId:"47285744566564", docIds:["spec","sds"] },
      { id:"agricultural-biochar", name:"100% Biochar", avail:"live", cat:"Biochar", category:"Soil Amendment · OMRI-listed", accent:"amber",
        claim:"OMRI-listed bagasse biochar holds about 3 to 3.5 times its weight in water for better moisture and nutrient retention.",
        uses:["Soil amendment for gardens, beds, and lawns","Water and nutrient retention","Supports faster compost cycles","Carbon-negative soil carbon storage"],
        chips:["½ lb sample bag","OMRI-listed","100% bagasse"], unit:"½ lb Sample Bag", sampleWeight:"½ LB", photo:ASSETS.biocharPhoto, free:true, truckloadQ4:true,
        bag:{ banner:"100% BIOCHAR", iconSet:"soil",
          icons:["Natural Biomass","Agricultural Waste","Superior Water Retention","Enhanced Root Development"],
          uses:"Garden & Lawn Soil Amendment | Vegetable & Flower Bed Enrichment | Tree & Orchard Planting | Farm & Crop Field Application | Improving Water-Holding Capacity | Boosting Nutrient Retention & Microbial Activity | Long-Term Carbon Sequestration in Soil",
          desc:"A pure, carbon-negative soil amendment made from Louisiana sugarcane bagasse. Our biochar's porous, honeycomb structure locks carbon into a stable form that can persist in soil for decades to millennia, while improving water retention, nutrient availability, and aeration. It's OMRI Listed for organic use, so it fits right into organic gardens, farms, and landscaping programs. Simply mix into soil, water thoroughly to activate, and let it get to work building healthier ground from the roots up.",
          ingredients:"MICROBE TREATED SUGARCANE BAGASSE", omri:true },
        desc:"OMRI-listed 100% bagasse biochar soil enhancer for healthy growth and carbon capture, made from pure Louisiana sugarcane fiber. It improves water and nutrient retention and holds about 3 to 3.5 times its weight in water. Works as a soil amendment for gardens, beds, lawns, and trees.",
        gallery:[ CDN+"100BiocharMock.jpg?v=1699279980", CDN+"AmericanBiocarbonBiochar1.jpg?v=1699279980", CDN+"1_45b3c726-d412-46ee-9b59-0347af6e854c.png?v=1699279980", CDN+"2_c0b4ae49-7772-478d-9cc8-71fb351a32b0.png?v=1699279980" ],
        sections:[
          { h:"How to use", body:"A general guideline is 10 to 25 pounds of biochar per 100 square feet. Loosen the soil and remove debris, remove 2 to 3 inches of topsoil, sprinkle the biochar, then replace the topsoil." },
          { h:"Water and monitor", body:"Water thoroughly to activate the product, saturating the soil to a depth of at least 6 inches. Check periodically so the soil stays moist but not waterlogged, and adjust the rate as needed. Add aggregates such as perlite if the soil retains too much water." },
          { h:"Water and nutrient retention", body:"OMRI-listed bagasse biochar holds about 3 to 3.5 times its weight in water, improving moisture and nutrient retention and supporting soil microbiology." },
        ],
        img:ASSETS.biocharMock, variantId:"46496458539300", docIds:["spec","sds"] },
      { id:"biosoil", name:"BioSoil", avail:"q4", cat:"Soil", category:"Growing Media · NPK-Enriched Blend", accent:"soil",
        claim:"Ready-to-use growing media with inherent NPK nutrients, biochar, and organic fiber in one locally blended formula.",
        uses:["Inherent NPK nutrients","Water & nutrient retention","Ready to use with no mixing"],
        chips:["½ lb sample bag","Locally sourced","Coming Q4"], sampleWeight:"½ LB", photo:ASSETS.biocharLg,
        bag:{ banner:"BIOSOIL · LOCALLY SOURCED GROWING MEDIA", iconSet:"soil",
          icons:["Locally Sourced","NPK-Enriched Blend","Superior Water Retention","Enhanced Root Development"],
          uses:"Potting & Container Gardening | Raised Beds & Garden Bed Fill | Tree & Shrub Planting | Starting Seedlings & Transplants | Improving Water Retention in Sandy or Fast-Draining Soil",
          desc:"Ready-to-use growing media blended from Louisiana-sourced materials: 40% proprietary microbe-treated multipurpose fiber, 40% carbon-negative bagasse biochar, and 20% coffee chaff. This unique formula delivers inherent nitrogen, phosphorus, and potassium alongside water retention, nutrient holding, and aeration benefits. Just add water. Ideal for potting, raised beds, landscape restoration, and growers who want a complete nutrient profile without mixing. Coming Q4.",
          ingredients:"MICROBE TREATED MULTIPURPOSE FIBER (40%), BAGASSE BIOCHAR (40%), COFFEE CHAFF (20%)", omri:true },
        img:ASSETS.biocharLg, docIds:["spec"] },
      { id:"absorbent-crumble", name:"Absorbent Crumble", avail:"q4", cat:"Absorbents", category:"Industrial Absorbent · Large-Area Spills", accent:"aqua",
        claim:"A coarser grade that spreads fast across a wide footprint with the same high capacity.",
        uses:["Large-area and high-volume spill coverage","Fast, broad application","Disaster and flood cleanup"],
        chips:["1 lb sample bag","Coarse grade","100% bagasse"], sampleWeight:"1 LB", photo:ASSETS.pelletsPhoto, img:ASSETS.pelletsMock, docIds:["spec"],
        bag:{ banner:"ABSORBENT CRUMBLE", iconSet:"absorbent",
          icons:["Natural Biomass","Agricultural Waste","Naturally Absorbent Fibers","Superior Liquid Retention"],
          uses:"Spill Cleanup (Oil, Solvents & Non-Viscous Chemicals) | Animal Bedding | Landfill Leachate Control | Oil & Gas Fluid Remediation (Drilling & Fracking) | Large-Area or High-Volume Spill Coverage",
          desc:"A carbon-neutral, plant-based absorbent made from sugarcane bagasse, offered in a coarser crumble form for faster, broader coverage. Like our standard pellets, the crumble soaks up several times its own weight in liquid, outperforming standard wood-based absorbents. Simply spread over the mess, let it fully absorb, then sweep up and dispose. Renewable, sustainably sourced, and built for demanding industrial and household cleanup jobs.",
          ingredients:"MICROBE TREATED SUGARCANE BAGASSE", omri:false } },
      { id:"absorbent-fiber", name:"Multipurpose Fiber", avail:"q4", cat:"Absorbents", category:"Peat Moss Replacement · Locally Sourced", accent:"aqua",
        claim:"Louisiana-sourced loose fiber for spill cleanup, animal bedding, and soil amendment—the core ingredient in BioSoil growing media. Coming Q4.",
        uses:["Loose fiber for multiple applications","Animal bedding and litter","Spill cleanup and remediation","Core component of BioSoil"],
        chips:["1 lb sample bag","Locally sourced","Peat alternative"], sampleWeight:"1 LB", photo:ASSETS.pelletsPhoto, img:ASSETS.pelletsMock, docIds:["spec"],
        bag:{ banner:"MULTIPURPOSE FIBER · LOCALLY SOURCED", iconSet:"absorbent",
          icons:["Locally Sourced","Agricultural Waste","Peat Replacement","Superior Absorption"],
          uses:"Animal Bedding & Litter | Spill Cleanup (Oil, Solvents & Non-Viscous Chemicals) | Landfill Leachate Control | Oil & Gas Fluid Remediation | Environmental Remediation | Core Component of BioSoil Growing Media",
          desc:"Louisiana-sourced, microbe-treated bagasse multipurpose fiber—a renewable peat-moss alternative engineered for versatility. Absorbs several times its own weight in liquid, outperforming wood-based absorbents, and spreads fast over wide areas. Use for industrial spill cleanup, animal bedding, or as the primary component in BioSoil growing media (launching Q4). Simply spread over the mess, let it fully absorb, then sweep up and dispose. Carbon-neutral, sustainably sourced, biodegradable, and locally grown.",
          ingredients:"MICROBE TREATED SUGARCANE BAGASSE FIBER", omri:false } },
      { id:"biochar-infused-soil", name:"Biochar-Infused Soil", avail:"q4", cat:"Soil", category:"Growing Media · Ready-to-Use Blend", accent:"soil",
        claim:"A ready-to-use growing soil pre-blended with our carbon-negative bagasse biochar. No mixing.",
        uses:["Potting and container gardening","Raised beds and garden bed fill","Water retention in sandy soil"],
        chips:["½ lb sample bag","Ready-to-use","Biochar-infused"], sampleWeight:"½ LB", photo:ASSETS.biocharLg, img:ASSETS.biocharLg, docIds:["spec"],
        bag:{ banner:"BIOCHAR-INFUSED SOIL", iconSet:"soil",
          icons:["Natural Biomass","Agricultural Waste","Superior Water Retention","Enhanced Root Development"],
          uses:"Potting & Container Gardening | Raised Beds & Garden Bed Fill | Lawn Patch & Overseeding Prep | Starting Seedlings & Transplants | Improving Water Retention in Sandy or Fast-Draining Soil",
          desc:"A ready-to-use growing soil pre-blended with our carbon-negative bagasse biochar, so you get the water retention, nutrient-holding, and soil-aeration benefits of biochar without any mixing or guesswork. Just fill your bed, pot, or planting hole and go. Built on the same sustainably sourced, Louisiana sugarcane biochar as our standalone soil amendment, this blend gives your plants a strong, carbon-rich foundation from the very first watering.",
          ingredients:"MICROBE TREATED SUGARCANE BAGASSE, BIOCHAR AND COFFEE CHAFF", omri:true } },
    ],
    filters:["All","Absorbents","Biochar","Soil"],
    bbqFootnote:{ label:"Louisiana Sweet BBQ Smoker Pellets (consumer/retail)", href:"https://americanbiocarbon.com/products/louisiana-sweet-bbq-smoker-pellets" },
  },
  categories:[
    { name:"Absorbent Pellets", icp:"Oil & gas · spill response · remediation", blurb:"Up to a 5:1 absorption ratio. Fewer bags, lighter disposal, low dust. Sample bags ship now.", cta:CTA.sample, href:"#/product/absorbent-pellets", img:ASSETS.pelletsMock, avail:"live" },
    { name:"100% Biochar", icp:"Distributors · blenders · growers", blurb:"OMRI-listed bagasse biochar holds ~3 to 3.5× its weight in water, better moisture retention, faster compost. Sample bags ship now.", cta:CTA.biochar, href:"#/product/agricultural-biochar", img:ASSETS.biocharMock, avail:"live" },
    { name:"Absorbent Crumble", icp:"Large-area & high-volume spills", blurb:"A coarser grade that spreads fast across a wide footprint, same high capacity.", cta:CTA.quote, href:"#/product/absorbent-crumble", img:ASSETS.pelletsMock, avail:"q4" },
    { name:"Biochar-Infused Soil", icp:"Landscape · nursery · retail", blurb:"Ready-to-use blend with biochar's water- and nutrient-holding benefits. No mixing.", cta:CTA.biochar, href:"#/product/biochar-infused-soil", img:ASSETS.biocharLg, avail:"q4" },
    { name:"Carbon Removal", icp:"Corporate ESG · brokers · marketplaces", blurb:"Puro.earth-certified CORCs generated by real biochar deployment, backed by MRV.", cta:CTA.carbon, href:"#/product/carbon-removal", img:ASSETS.hands, avail:"q4" },
  ],
  socialProof:{
    placeholder:true, // SCAFFOLD, replace with real, verifiable proof before publishing
    kicker:"Trusted in the field",
    h:"Proof from the operations that switched",
    sub:"Placeholder scaffold, swap in real customer logos, results, and quotes once approved for use.",
    logos:["Your Customer","Logo Here","Operator Co.","Distributor Inc.","Refinery Group","Compost Yard"],
    stats:[
      { n:"N/A", l:"Disposal weight reduced vs. previous sorbent", note:"Add a real, sourced figure" },
      { n:"N/A", l:"Bags saved per average spill", note:"Add a real, sourced figure" },
      { n:"N/A", l:"Tons deployed / CORCs issued", note:"Add a real, sourced figure" },
    ],
    quote:{ text:"Add a real customer quote here, the specific, measurable outcome a buyer got after switching. Keep it defensible and attributable.", who:"Name, Title", org:"Company (with permission to cite)" },
  },
  feature:{
    kicker:"Oil & Gas · Industrial Remediation",
    h:"Engineered for the field",
    body:"Solidify drilling and frac fluids, clean up oil and non-viscous chemical spills, and control landfill leachate with a renewable sorbent that cuts bag count and disposal weight. Available in bulk, one-metric-ton bulk bags, and truckload volumes, with SDS and spec sheets on request.",
    bullets:[
      "Drilling & frac fluid solidification",
      "Oil & non-viscous chemical spill cleanup",
      "Landfill leachate control",
      "Industrial aqueous waste streams",
      "Bulk, bulk-bag & truckload supply",
      "SDS + spec sheet on request",
    ],
    primary:CTA.specialist, secondary:CTA.sample, image:ASSETS.pelletsPhoto,
  },
  comparison:{
    h:"5:1 vs 2.5:1, the same spill, roughly half the bags",
    sub:"Absorbency numbers reflect available product data for non-viscous liquids. Request the spec sheet for test conditions.",
    cols:["Property","Bagasse Pellets","Wood Pellets","Clay Absorbent"],
    rows:[
      ["Absorption (liquid : sorbent)","Up to ~5:1","~2.5:1","Low (heavy)"],
      ["Bags per spill","Fewest","~2× more","Most"],
      ["Disposal weight","Lightest","Heavier","Heaviest"],
      ["Renewable / plant-based","Yes","Yes","No"],
      ["Dust","Low","Moderate","High"],
      ["Carbon story","Carbon-negative","Neutral","None"],
    ],
    cta:CTA.compare,
  },
  ag:{
    kicker:"Agriculture & Soil",
    h:"Healthier soil, faster compost",
    body:"OMRI-listed bagasse biochar holds ~3 to 3.5× its weight in water (per technical report) and improves nutrient retention, so blends hold moisture through dry spells and leach less fertilizer. Based on peer-reviewed research on biochar in composting, it can help shorten compost turnover ~10 to 30% (validate in your own process). For distributors, soil blenders, compost yards, growers, and landscape supply.",
    bullets:["Holds ~3 to 3.5× its weight in water","Can help shorten compost cycles ~10 to 30% (research)","Inherent nutrients + microbial habitat","Bulk, bulk-bag & bagged formats"],
    primary:CTA.distributor, secondary:CTA.biochar, image:ASSETS.biocharLg,
  },
  carbon:{
    kicker:"The dual-revenue engine",
    h:"Every ton deployed is also durable carbon removal",
    body:"When our biochar is deployed, its stable carbon is locked away for the long term, certified through Puro.earth and issued as CORCs tied to real, documented deployment, not paper offsets. The physical product and the carbon value move on the same molecule.",
    lead:"This is what makes American BioCarbon un-commoditizable: the same tons that solve a spill or amend a field generate verified carbon removal. It's one supply chain, two revenue streams, and a defensible story for both the buyer and the market.",
    audiences:[
      { who:"For industrial & ag buyers", val:"Your remediation and soil spend funds verified, MRV-backed carbon removal, a cleaner materials story you can put in front of clients and HSE." },
      { who:"For corporate ESG & brokers", val:"Durable, deployment-backed CORCs with an audit trail, real removed tons via Puro.earth, not avoidance offsets that fail scrutiny." },
    ],
    metrics:[
      { n:"H/C < 0.7", l:"Durable-carbon threshold (lab-verified)" },
      { n:"Puro.earth", l:"Certified CORC methodology" },
      { n:"MRV-backed", l:"Deployment-based measurement & reporting" },
    ],
    primary:CTA.carbon, secondary:CTA.spec, image:ASSETS.hands,
  },
  audience:{
    kicker:"Find your line in 10 seconds",
    h:"What are you here to solve?",
    sub:"Pick the path that fits your role, we'll take you straight to the right products, specs, and request form.",
    lanes:[
      { tag:"Oil, Gas & Industrial", desc:"Solidify drilling & frac fluids, remediate sites, fewer bags, lighter disposal.", href:"#/industry/oil-gas", cta:"Industrial absorbents" },
      { tag:"Spill Response & Disaster", desc:"More capture per bag for emergency crews and large-area cleanup.", href:"#/industry/spill-response", cta:"Spill-response line" },
      { tag:"Landfill & Waste", desc:"Solidify leachate and aqueous waste with RFP-ready documentation.", href:"#/industry/landfill-leachate", cta:"Leachate solutions" },
      { tag:"Ag Distributors & Growers", desc:"Add a carbon-negative, OMRI-listed biochar line with a margin model.", href:"#/industry/distributors", cta:"Distributor program" },
      { tag:"Soil Blenders & Composters", desc:"Research points to ~10 to 30% faster compost turnover (validate in your process); holds ~3 to 3.5× its weight in water in blends.", href:"#/industry/soil-blenders", cta:"Blender & compost" },
      { tag:"Corporate ESG & Carbon", desc:"Durable, deployment-backed CORCs via Puro.earth, not paper offsets.", href:"#/product/carbon-removal", cta:"Carbon removal" },
    ],
  },
  useCases:["Drilling & frac fluids","Spill response","Landfill leachate","Flood & disaster cleanup","Animal bedding","Soil amendment","Compost & blending","Carbon removal"],
  finalCta:{
    h:"Put it to the test",
    sub:"Request an industrial sample kit or a bulk quote. A specialist replies within one business day, with the SDS and spec sheet attached.",
    primary:CTA.sample, secondary:CTA.quote, tertiary:CTA.specialist,
  },
};

/* ============ PRODUCTS ============ */
const PRODUCTS = {
  "absorbent-pellets":{
    name:"Absorbent Pellets", icp:"Oil & gas · spill response · environmental remediation · landfill",
    intent:"Evaluate & procure an industrial sorbent",
    seo:{ title:"Industrial Absorbent Pellets, 5:1 Bagasse Sorbent | American BioCarbon",
      desc:"Plant-based bagasse absorbent pellets that hold up to 5× their weight in liquid, vs ~2.5× for wood. Fewer bags, lighter disposal. Bulk supply, SDS & spec on request.",
      slug:"/absorbent-pellets", keyword:"industrial absorbent pellets",
      secondary:["oil spill absorbent pellets","plant-based absorbent","wood pellet alternative absorbent","biodegradable absorbent pellets"],
      schema:"Product + FAQPage + BreadcrumbList" },
    h1:"Industrial Absorbent Pellets That Hold up to 5× Their Weight",
    sub:"A plant-based bagasse sorbent for drilling fluids, spills, and leachate, holding up to ~5× its weight vs about 2.5× for wood pellets means roughly half the bags and lighter saturated disposal per spill, plus low dust.",
    primary:CTA.sample, secondary:CTA.quote, tertiary:CTA.sds, image:ASSETS.pelletsPhoto, mock:ASSETS.pelletsMock,
    proofRow:["Up to 5:1 absorption","100% organic biomass (no additives)","~32 lb/ft³ bulk density","Free 1-lb sample · volume supply Q4"],
    problem:{ h:"You're paying to buy and dispose of material that barely holds its own weight",
      body:"At ~2.5:1, wood pellets take roughly 2× the bags per spill and send more saturated weight to disposal, and disposal is billed by the pound, so more weight means more tipping cost and more truckloads hauled. Clay is heavier still and adds non-renewable waste. Crews want fewer bags to handle; procurement wants documentation and reliable supply." },
    explanation:{ h:"Why bagasse absorbs more",
      body:"Sugarcane bagasse has a naturally ordered, honeycomb-like pore structure. Carbonized and processed into pellets, that structure gives it a high capacity to draw in and hold liquid, up to roughly 5× its weight for non-viscous liquids. It's 100% organic biomass with no chemical additives, low dust, and renewable." },
    useCases:["Drilling & frac fluid solidification","Oil & fuel spill cleanup","Non-viscous chemical spills","Landfill leachate control","Flood & disaster cleanup","Soil runoff absorption"],
    specs:[
      ["Absorption ratio","Up to ~5:1 (liquid : sorbent), non-viscous"],
      ["Material","100% organic sugarcane bagasse, no additives"],
      ["Bulk density","~32 lb/ft³ (≈510 kg/m³)"],
      ["Availability","Free 1-lb samples now; bulk & 1-MT-bag supply from Q4"],
      ["Dust","Low"],
      ["Documentation","SDS + spec sheet on request"],
    ],
    comparison:{ h:"Vs the status quo",
      cols:["","Bagasse Pellets","Wood Pellets","Clay"],
      rows:[["Absorption","~5:1","~2.5:1","Low"],["Bags per job","Fewest","~2× more","Most"],["Disposal weight","Lightest","Heavier","Heaviest"],["Renewable","Yes","Yes","No"]] },
    faq:[
      { q:"What liquids do the pellets absorb?", a:"Oil, fuels, and non-viscous chemicals and aqueous streams. For a specific fluid, request the spec sheet and SDS so we can confirm suitability." },
      { q:"How is it disposed of?", a:"Saturated material is swept up and disposed of per your local requirements and the absorbed material's profile. Because it holds up to ~5× its weight vs ~2.5× for wood, you fill roughly half the bags and send less saturated weight to disposal, fewer pounds at by-the-pound rates and fewer truckloads." },
      { q:"Can I get a sample, and when is volume supply available?", a:"Yes, free 1-lb samples ship now (4 to 7 business days) so you can test against your current absorbent. Volume supply (bulk, one-metric-ton bags, truckload) comes online with our Q4 capacity ramp; if the sample performs, you can reserve supply and lock pricing now." },
      { q:"Do you provide an SDS and spec sheet?", a:"Yes, both are available on request and sent automatically when you submit a sample or quote request." },
    ],
    form:"sample",
    internal:["#/product/absorbent-crumble","#/industry/oil-gas","#/industry/landfill-leachate","#/technical"],
  },
  "absorbent-crumble":{
    name:"Absorbent Crumble", icp:"Large-area & high-volume spill coverage",
    intent:"Procure a fast-spreading absorbent",
    seo:{ title:"Absorbent Crumble, Fast, Broad Coverage Bagasse Sorbent | American BioCarbon",
      desc:"A coarser bagasse absorbent crumble for large-area and high-volume spills. Spreads fast, holds up to 5× its weight. Bulk supply, SDS & spec on request.",
      slug:"/absorbent-crumble", keyword:"absorbent crumble",
      secondary:["large area spill absorbent","high volume spill absorbent","plant-based absorbent"],
      schema:"Product + FAQPage" },
    h1:"Absorbent Crumble for Fast, Broad Coverage",
    sub:"A coarser bagasse form that spreads quickly across large-area and high-volume spills, same up-to-5:1 performance, faster to lay down.",
    primary:CTA.quote, secondary:CTA.sample, tertiary:CTA.sds, image:ASSETS.pelletsPhoto, mock:ASSETS.pelletsMock,
    proofRow:["Up to 5:1 absorption","Coarse, fast-spreading","100% organic biomass","Bulk & truckload"],
    problem:{ h:"Big spills need coverage speed, not just capacity",
      body:"On large-area or high-volume events, how fast you can lay material down drives labor hours, every extra minute spreading is a crew on the clock and a spill still migrating. Fine pellets spread slower across a wide footprint, so they take more passes and more labor to cover the same area." },
    explanation:{ h:"Coarser by design",
      body:"Crumble is the same 100% bagasse sorbent in a coarser texture that spreads faster and covers more ground per pass, while still soaking up several times its weight in liquid." },
    useCases:["Large-area spill coverage","High-volume events","Disaster & flood cleanup","Industrial washdown areas","Oil & gas fluid remediation"],
    specs:[
      ["Absorption ratio","Up to ~5:1, non-viscous"],
      ["Texture","Coarse crumble (faster spread)"],
      ["Material","100% organic sugarcane bagasse"],
      ["Form factors","Bulk · 1-metric-ton bulk bag"],
      ["Documentation","SDS + spec sheet on request"],
    ],
    comparison:{ h:"Crumble vs pellets",
      cols:["","Crumble","Pellets"],
      rows:[["Coverage speed","Faster","Standard"],["Best for","Large-area / high-volume","Targeted spills"],["Absorption","~5:1","~5:1"]] },
    faq:[
      { q:"When should I use crumble vs pellets?", a:"Choose crumble for large-area or high-volume spills where fast, broad coverage matters; choose pellets for targeted cleanup." },
      { q:"What volumes are available?", a:"Bulk and one-metric-ton bulk bags; truckload on request." },
    ],
    form:"quote",
    internal:["#/product/absorbent-pellets","#/industry/spill-response","#/industry/industrial-remediation","#/technical"],
  },
  "agricultural-biochar":{
    name:"100% Biochar", icp:"Ag distributors · soil blenders · compost yards · growers",
    intent:"Source a differentiated organic soil amendment / resale SKU",
    seo:{ title:"Bagasse Biochar, OMRI-Listed Sugarcane Soil Amendment | American BioCarbon",
      desc:"OMRI-listed bagasse biochar for water and nutrient retention and faster compost. Bulk supply for distributors, blenders, and growers. Request a sample or distributor pricing.",
      slug:"/agricultural-biochar", keyword:"bagasse biochar",
      secondary:["sugarcane biochar","organic biochar soil amendment","OMRI biochar","biochar for water retention","biochar soil amendment bulk","compost biochar additive"],
      schema:"Product + FAQPage + BreadcrumbList" },
    h1:"OMRI-Listed Bagasse Biochar for Water &amp; Nutrient Retention",
    sub:"A locally sourced, carbon-negative sugarcane biochar that improves water and nutrient retention, supports soil microbiology, and can help shorten compost turnover ~10 to 30%. Core ingredient in BioSoil growing media (launching Q4).",
    primary:CTA.biochar, secondary:CTA.distributor, tertiary:CTA.spec, image:ASSETS.biocharPhoto, mock:ASSETS.biocharMock,
    proofRow:["OMRI Listed · IBI Certified","Holds ~3 to 3.5× its weight in water","Inherent NPK + Ca/Mg","Free sample · volume supply Q4"],
    problem:{ h:"Distributors and blenders need a differentiated line that actually pulls through",
      body:"Commodity amendments compete on price alone, every reorder shaves the margin thinner, and an undifferentiated bag only moves when it's the cheapest on the shelf. Growers increasingly ask for water efficiency, organic inputs, and a carbon story, and composters and blenders need throughput and consistent quality, not another line that races price to the bottom." },
    explanation:{ h:"Louisiana-sourced biochar: versatile soil amendment and BioSoil foundation",
      body:"Bagasse biochar's honeycomb pore structure holds roughly 3 to 3.5× its weight in water, retains nutrients, and provides protected habitat for soil microbes. Unlike most wood biochar, it carries inherent nutrients (~0.6-0.2-0.7 NPK plus calcium and magnesium). It's OMRI listed and IBI certified, with heavy metals well below IBI and EPA Class A thresholds. Use it standalone for soil amendment and composting, or as 40% of BioSoil—our locally sourced growing media launching Q4, blended with multipurpose fiber and coffee chaff for peat-moss performance." },
    useCases:["Soil amendment (sandy/degraded soils)","Compost acceleration & bulking","Premium blend component","Nursery & greenhouse media","Row-crop & specialty ag trials"],
    specs:[
      ["Organic carbon","~58 to 65% (dry basis)"],
      ["Water-holding","~3 to 3.5× its weight (per technical report)"],
      ["Nutrients","Inherent NPK ~0.6-0.2-0.7 + Ca/Mg"],
      ["H/C molar ratio","<0.7 (durable carbon)"],
      ["Certifications","OMRI Listed · IBI Certified · USDA Organic pending"],
      ["Availability","Free 8-oz samples now; bulk, 1-MT-bag & bagged supply from Q4"],
    ],
    comparison:{ h:"Bagasse vs wood biochar",
      cols:["","Bagasse","Wood"],
      rows:[["Pore structure","Ordered honeycomb","Random/fractured"],["Water-holding","~3 to 3.5×","~2×"],["Inherent nutrients","Yes","Minimal"],["Best for","Sandy/degraded, compost","Structural only"]] },
    faq:[
      { q:"Is it certified organic?", a:"It is OMRI Listed and IBI Certified. USDA Organic certification is pending, we don't present it as certified until it is." },
      { q:"Can it speed up composting?", a:"Peer-reviewed research shows biochar can shorten compost cycles ~10 to 30% and raise pile temperature, shorter cycles mean more batches through the same windrow footprint. We recommend a side-by-side windrow trial to measure the effect in your own operation." },
      { q:"What are the distributor terms?", a:"Start with a free sample and a preview of the margin model. Full stocking volume comes online with our Q4 capacity ramp, distributors can reserve territory and lock pricing now." },
    ],
    form:"biochar",
    internal:["#/industry/distributors","#/industry/soil-blenders","#/product/biochar-infused-soil","#/technical"],
  },
  "biochar-infused-soil":{
    name:"Biochar-Infused Soil", icp:"Landscape · nursery · retail · growers",
    intent:"Buy a ready-to-use biochar blend",
    seo:{ title:"Biochar-Infused Soil, Ready-to-Use Amendment | American BioCarbon",
      desc:"A ready-to-use soil pre-blended with carbon-negative bagasse biochar for water retention and nutrient holding. No mixing. Request a sample.",
      slug:"/biochar-infused-soil", keyword:"biochar soil amendment",
      secondary:["ready to use biochar soil","biochar for water retention","carbon-negative soil amendment"],
      schema:"Product + FAQPage" },
    h1:"Ready-to-Use Biochar Soil, No Mixing",
    sub:"A growing soil pre-blended with carbon-negative bagasse biochar, so you get the water-holding, nutrient-retention, and aeration benefits from the first watering.",
    primary:CTA.biochar, secondary:CTA.distributor, tertiary:CTA.spec, image:ASSETS.biocharLg, mock:ASSETS.biocharMock,
    proofRow:["Pre-blended, no mixing","OMRI-listed biochar base","Water & nutrient retention","Bagged & bulk"],
    problem:{ h:"Not everyone wants to blend biochar themselves",
      body:"Landscapers, nurseries, and retail buyers want the performance without the guesswork of dosing and mixing raw biochar into their media." },
    explanation:{ h:"The benefits, ready to use",
      body:"Built on the same Louisiana sugarcane biochar as our standalone amendment, this blend delivers water retention, nutrient holding, and aeration with no mixing, fill a bed, pot, or planting hole and go." },
    useCases:["Raised beds & garden fill","Container & nursery media","Tree & shrub planting","Seedlings & transplants","Sandy or fast-draining soils"],
    specs:[
      ["Base","Carbon-negative bagasse biochar blend"],
      ["Benefit","Water retention · nutrient holding · aeration"],
      ["Prep","Ready to use, no mixing"],
      ["Form factors","Bagged · bulk"],
    ],
    comparison:{ h:"Blend vs raw biochar",
      cols:["","Infused Soil","Raw Biochar"],
      rows:[["Prep","None","Dose & mix"],["Best for","Ready-to-plant","Blenders/growers who dose"]] },
    faq:[
      { q:"Do I need to charge or activate it?", a:"No, it's ready to use. Water thoroughly at planting." },
      { q:"Is bulk available?", a:"Yes, alongside bagged. Request a sample or quote with your volume." },
    ],
    form:"biochar",
    internal:["#/product/agricultural-biochar","#/industry/distributors","#/technical"],
  },
  "carbon-removal":{
    name:"Carbon Removal Credits (CORCs)", icp:"Corporate ESG · carbon brokers · marketplaces",
    intent:"Source durable, verifiable carbon removal",
    seo:{ title:"Biochar Carbon Removal Credits (CORCs), Puro.earth Certified | American BioCarbon",
      desc:"Durable, deployment-backed biochar carbon removal certified through Puro.earth. Real deployed tons with MRV, not paper offsets. Request carbon removal information.",
      slug:"/carbon-removal", keyword:"biochar carbon removal",
      secondary:["carbon removal credits biochar","Puro.earth biochar","durable carbon removal","carbon-negative soil amendment"],
      schema:"Service + FAQPage" },
    h1:"Durable, Deployment-Backed Carbon Removal",
    sub:"Puro.earth-certified CORCs generated when our biochar is physically deployed, backed by measurement, reporting, and verification.",
    primary:CTA.carbon, secondary:CTA.specialist, image:ASSETS.hands, mock:ASSETS.biocharMock,
    proofRow:["Puro.earth certified","H/C < 0.7 · durable","Physical deployment + MRV"],
    problem:{ h:"Buyers need credits that survive scrutiny",
      body:"Corporate buyers under pressure to source durable, verifiable carbon removal must defend every ton to auditors. Many credits are paper avoidance offsets with uncertain permanence that get written down or retired-in-doubt when scrutinized." },
    explanation:{ h:"Real tons, documented from the ground up",
      body:"Our biochar locks carbon into a stable form (H/C < 0.7) that persists long-term. Credits are tied to documented, physical deployment of product through Puro.earth, grounding supply in real tons moved with a complete MRV trail." },
    useCases:["Corporate net-zero procurement","Carbon broker sourcing","Forward purchase contracts"],
    specs:[
      ["Durability","H/C < 0.7 (millennial-scale storage)"],
      ["Verification","Puro.earth CORC + independent MRV"],
      ["Supply","Documented physical biochar deployment"],
    ],
    comparison:{ h:"Real tons vs paper offsets",
      cols:["","Our CORCs","Typical offsets"],
      rows:[["Basis","Physical biochar deployment","Paper/avoidance claims"],["Durability","Stable biochar form","Variable"],["Permanence","1000+ years","Uncertain"]] },
    faq:[
      { q:"What's the CO₂ per ton?", a:"We share verified methodology-specific figures during diligence. Request information and we'll provide current data aligned to our deployment pipeline." },
      { q:"Forward purchase options?", a:"Yes, sized conservatively to our deployment schedule—we don't sell more credits than deployable tons." },
    ],
    form:"carbon",
    internal:["#/product/agricultural-biochar","#/about"],
  },
  "biosoil":{
    name:"BioSoil", icp:"Growers · nurseries · landscape · soil blenders",
    intent:"Source a ready-to-use peat-moss alternative with local sourcing",
    seo:{ title:"BioSoil Growing Media, Locally Sourced Peat Alternative | American BioCarbon",
      desc:"Ready-to-use locally sourced growing media: 40% multipurpose fiber, 40% biochar, 20% coffee chaff. Peat-free performance, no mixing. Coming Q4.",
      slug:"/biosoil", keyword:"peat moss alternative",
      secondary:["locally sourced growing media","peat-free soil amendment","biochar growing media","ready-to-use potting soil"],
      schema:"Product + FAQPage + BreadcrumbList" },
    h1:"BioSoil: Locally Sourced Peat-Moss Alternative Growing Media",
    sub:"A ready-to-use growing media blended from Louisiana-sourced materials: 40% microbe-treated multipurpose fiber, 40% carbon-negative biochar, 20% coffee chaff. Performs like peat moss—water retention, nutrient holding, aeration—with no mixing and no mined bog. Coming Q4.",
    primary:CTA.biochar, secondary:CTA.distributor, tertiary:CTA.quote, image:ASSETS.biocharLg, mock:ASSETS.biocharMock,
    proofRow:["Locally sourced","Peat-free formula","Water & nutrient retention","Ready to use"],
    problem:{ h:"Peat moss is mined, depletes bogs, and growers need alternatives that actually perform",
      body:"Traditional peat harvesting drains irreplaceable wetlands and contributes to greenhouse gas emissions. Growers demand peat-free alternatives, but most replacements either require mixing or underperform on water retention and nutrient cycling. BioSoil eliminates the compromise." },
    explanation:{ h:"Locally blended for performance and sustainability",
      body:"BioSoil combines three Louisiana-sourced components: microbe-treated multipurpose fiber (40%) for structure and water holding, carbon-negative bagasse biochar (40%) for nutrient retention and microbial habitat, and coffee chaff (20%) for gentle nutrient contribution. The result is ready-to-use growing media that delivers peat-moss performance without mining or mixing." },
    useCases:["Potting and container gardening","Raised beds and garden fill","Landscape and restoration planting","Nursery and greenhouse production","Seedling and transplant starting"],
    specs:[
      ["Composition","40% multipurpose fiber, 40% biochar, 20% coffee chaff"],
      ["Water holding","~3 to 3.5× weight in water"],
      ["Inherent nutrients","Balanced NPK from coffee chaff"],
      ["Application","Ready to use, no mixing required"],
      ["Availability","Coming Q4 · sample orders starting now"],
    ],
    comparison:{ h:"BioSoil vs Traditional Peat Moss",
      cols:["Property","BioSoil","Traditional Peat Moss"],
      rows:[["Source","Locally sourced (Louisiana)","Mined peat bogs"],["Water retention","~3 to 3.5× weight in water","~2 to 3× weight in water"],["Nutrient content","Inherent NPK from coffee chaff","Minimal nutrients"],["Prep required","Ready to use","May require amendment"],["Carbon impact","Carbon-negative biochar","Harvesting releases CO₂"],["Bog impact","None—protects wetlands","Drains and damages bogs"],["Cost","Competitive bulk pricing","Higher resource cost"],["Renewable","100% renewable sources","Finite resource"]] },
    faq:[
      { q:"Is BioSoil certified organic?", a:"BioSoil is OMRI-listed for organic use. All components (biochar, fiber, coffee chaff) meet organic growing standards." },
      { q:"Do I need to mix it or add nutrients?", a:"No. BioSoil is ready to use straight from the bag. The inherent NPK and microbial community support plant growth without amendment." },
      { q:"When is BioSoil available?", a:"Samples are available now for Q4 pre-order. Full volume supply launches in Q4 2024." },
      { q:"What sizes are available?", a:"Launching with ½ lb sample bags for grower trials, then bulk and bagged formats for Q4 and beyond." },
    ],
    form:"biochar",
    internal:["#/product/agricultural-biochar","#/product/absorbent-fiber","#/technical"],
  },
};

/* ============ INDUSTRIES ============ */
const INDUSTRIES = {
  "oil-gas":{
    name:"Oil & Gas Remediation", icp:"Oilfield services · procurement · HSE",
    seo:{ title:"Drilling & Frac Fluid Absorbent, Plant-Based, 5:1 | American BioCarbon",
      desc:"Solidify drilling and frac fluids and clean spills with a plant-based absorbent that holds up to 5× its weight, fewer bags, lighter disposal. Bulk supply, SDS on request.",
      slug:"/industries/oil-gas", keyword:"drilling fluid absorbent",
      secondary:["fracking fluid remediation absorbent","oil spill absorbent pellets","industrial absorbent pellets"],
      schema:"Service + FAQPage" },
    h1:"Solidify Drilling &amp; Frac Fluids With Half the Bags",
    sub:"A plant-based bagasse absorbent for oilfield fluid solidification and spill cleanup, up to 5:1 absorption vs ~2.5:1 for wood, with SDS and bulk supply.",
    primary:CTA.sample, secondary:CTA.quote, image:ASSETS.pelletsPhoto,
    problem:"Oilfield disposal is billed by weight, so the sorbent you spread comes back as tonnage you pay to haul. At ~2.5:1, wood pellets take roughly twice the sorbent mass to solidify the same fluid, so you buy and bag more, and send heavier saturated loads to the disposal scale. And HSE teams face growing pressure to show a cleaner materials story.",
    fit:"Bagasse pellets and crumble solidify aqueous drilling and frac fluids and absorb oil and non-viscous chemical spills at up to 5× their weight (vs ~2.5:1 wood), so it can take up to about half the sorbent mass to lock up the same fluid, cutting bags per job and saturated weight to disposal, while giving HSE a renewable, carbon-negative material.",
    useCases:["Drilling & frac fluid solidification","Rig & site spill cleanup","Tank & pit fluid handling","Non-viscous chemical spills"],
    proof:["Up to 5:1 absorption (non-viscous)","SDS on request","Bulk, bulk-bag & truckload","Carbon-negative material"],
    procurement:["SDS + spec sheet provided","Bulk / bulk-bag / truckload formats","Freight-zoned pricing from White Castle, LA","Trial pallet available for head-to-head field test"],
    faq:[
      { q:"Can it handle water-based drilling fluids?", a:"Yes, it's used to solidify aqueous fluids and non-viscous streams. Share your fluid profile and we'll confirm fit and send the SDS." },
      { q:"How fast can we get a trial pallet?", a:"Request a sample kit with your site location; we'll stage a trial pallet for your next job." },
    ],
    form:"sample",
    products:["absorbent-pellets","absorbent-crumble"],
  },
  "industrial-remediation":{
    name:"Industrial Remediation", icp:"Environmental remediation firms · industrial ops",
    seo:{ title:"Plant-Based Industrial Absorbent for Remediation | American BioCarbon",
      desc:"A renewable industrial absorbent for spill and fluid remediation, holds up to 5× its weight, fewer bags, lighter disposal. Bulk supply, SDS & spec on request.",
      slug:"/industries/industrial-remediation", keyword:"industrial absorbent",
      secondary:["environmental remediation absorbent","plant-based absorbent","spill response absorbent"],
      schema:"Service + FAQPage" },
    h1:"A Renewable Industrial Absorbent That Cuts Bag Count",
    sub:"For remediation firms and industrial operations that need field performance, dependable supply, and documentation on one material.",
    primary:CTA.specialist, secondary:CTA.quote, image:ASSETS.pelletsPhoto,
    problem:"Remediation crews carry and dispose of enormous absorbent volume, and disposal is priced by the ton. At ~2.5:1, a lower-capacity sorbent takes roughly twice the sorbent mass to capture the same liquid, heavier saturated loads to the landfill, plus the extra bags and labor to move it. Clients increasingly want a sustainability story behind the cleanup too.",
    fit:"Bagasse pellets and crumble absorb up to 5× their weight in non-viscous liquids (vs ~2.5:1 wood), up to about half the sorbent mass per job, so fewer bags to move and less saturated weight billed at the disposal scale, with SDS and spec documentation and reliable bulk supply.",
    useCases:["Spill cleanup","Aqueous waste solidification","Site remediation","Industrial washdown"],
    proof:["Up to 5:1 absorption","SDS + spec on request","Bulk & truckload supply","Renewable, low-dust"],
    procurement:["Documentation package (SDS, spec)","Bulk / bulk-bag / truckload","Freight-aware pricing","Trial before switching"],
    faq:[
      { q:"Do you supply documentation for our clients?", a:"Yes, SDS and spec sheets are available on request and included when you submit a sample or quote request." },
    ],
    form:"quote",
    products:["absorbent-pellets","absorbent-crumble"],
  },
  "environmental-remediation":{
    name:"Environmental Remediation", icp:"Remediation contractors · environmental firms",
    seo:{ title:"Environmental Remediation Absorbent, Plant-Based, 5:1 | American BioCarbon",
      desc:"A renewable absorbent for soil, groundwater, and environmental remediation. Holds up to 5× its weight, fewer bags, lower disposal costs. Bulk supply, SDS on request.",
      slug:"/industries/environmental-remediation", keyword:"environmental remediation absorbent",
      secondary:["soil remediation absorbent","environmental cleanup absorbent","plant-based absorbent"],
      schema:"Service + FAQPage" },
    h1:"Environmental Remediation With a Renewable, High-Performance Absorbent",
    sub:"A plant-based bagasse absorbent engineered for soil, groundwater, and environmental site remediation, up to 5:1 capacity, fewer bags, lower disposal costs.",
    primary:CTA.specialist, secondary:CTA.quote, image:ASSETS.pelletsPhoto,
    problem:"Environmental remediation requires handling large volumes of contaminated soil and aqueous waste at a cost-per-ton disposal scale. At ~2.5:1, a lower-capacity sorbent takes roughly twice the sorbent mass to capture the same volume, heavier saturated loads to disposal, plus the extra material handling and ESG exposure. Site managers increasingly need a sustainability story to go with compliance.",
    fit:"Bagasse pellets and crumble absorb up to 5× their weight in non-viscous liquids and aqueous waste (vs ~2.5:1 wood), up to about half the sorbent mass per job, so fewer bags to handle and less saturated weight billed at the disposal scale, with SDS and spec documentation, renewable credentials, and dependable bulk supply.",
    useCases:["Soil remediation & cleanup","Groundwater & aqueous waste capture","Site spill containment","Contamination mitigation"],
    proof:["Up to 5:1 absorption","SDS + spec on request","Bulk & truckload supply","100% renewable material"],
    procurement:["Documentation package (SDS, spec)","Bulk / bulk-bag / truckload","Freight-aware pricing","Trial pilot available"],
    faq:[
      { q:"How does your absorbent handle contaminated soil?", a:"Our bagasse pellets and crumble capture non-viscous liquids and aqueous waste at up to 5:1. Share your contamination profile and we'll confirm fit and send the SDS with application guidance." },
      { q:"Can we run a site trial?", a:"Yes, we support pilot testing at the site with the full documentation package (SDS, spec, certifications) to confirm performance on your specific remediation challenge." },
    ],
    form:"quote",
    products:["absorbent-pellets","absorbent-crumble"],
  },
  "spill-response":{
    name:"Spill Response", icp:"Spill-response contractors · emergency crews",
    seo:{ title:"Spill Response Absorbent, Fewer Bags, Faster Cleanup | American BioCarbon",
      desc:"A plant-based spill-response absorbent that holds up to 5× its weight, fewer bags on the truck, faster cleanup, lighter disposal. Bulk supply, SDS on request.",
      slug:"/industries/spill-response", keyword:"spill response absorbent",
      secondary:["oil spill absorbent pellets","disaster cleanup absorbent","plant-based absorbent"],
      schema:"Service + FAQPage" },
    h1:"More Capture Per Bag. Fewer Trips to Disposal.",
    sub:"A bagasse absorbent built for spill-response crews, soaks up more per bag so you carry less, sweep up clean, and haul lighter.",
    primary:CTA.sample, secondary:CTA.quote, image:ASSETS.pelletsPhoto,
    problem:"On a spill, every bag is truck space, labor, and disposal weight you pay for. At ~2.5:1, a low-capacity sorbent takes roughly twice the mass to soak up the same volume, more bags loaded, more saturated weight hauled, more trips to the disposal scale.",
    fit:"Pellets for targeted spills, crumble for large-area coverage, both absorb up to 5× their weight (vs ~2.5:1 wood), so crews can capture the same spill with up to about half the sorbent mass: fewer bags on the truck, less saturated weight to the disposal scale.",
    useCases:["Oil & fuel spills","Non-viscous chemical spills","Flood & disaster cleanup","Roadway & site incidents"],
    proof:["Up to 5:1 absorption","Pellet & crumble forms","Low dust","SDS on request"],
    procurement:["Rapid-ship bulk supply","SDS + spec","Trial pallet","Standing reorder terms"],
    faq:[
      { q:"Which form for a large spill?", a:"Use crumble for fast, broad coverage on large-area events; pellets for targeted cleanup." },
    ],
    form:"sample",
    products:["absorbent-pellets","absorbent-crumble"],
  },
  "landfill-leachate":{
    name:"Landfill Leachate", icp:"Landfill operators · waste management · public works",
    seo:{ title:"Landfill Leachate Absorbent, Solidify Aqueous Waste at 5:1 | American BioCarbon",
      desc:"Solidify leachate and aqueous waste with a plant-based absorbent that holds up to 5× its weight. Renewable, low-dust, bulk supply. SDS & spec on request.",
      slug:"/industries/landfill-leachate", keyword:"landfill leachate absorbent",
      secondary:["leachate solidification","aqueous waste absorbent","plant-based absorbent"],
      schema:"Service + FAQPage" },
    h1:"Solidify Leachate With a Renewable, High-Capacity Sorbent",
    sub:"A plant-based bagasse absorbent for landfill leachate and aqueous waste solidification, up to 5:1 capacity, low dust, and reliable bulk supply.",
    primary:CTA.specialist, secondary:CTA.quote, image:ASSETS.pelletsPhoto,
    problem:"Leachate and aqueous waste handling is a recurring, weight-billed disposal cost and a compliance exposure. At ~2.5:1, a low-capacity sorbent takes roughly twice the sorbent mass to solidify the same volume, heavier saturated tonnage back out the gate, and dusty product adds handling and air exposure on top.",
    fit:"Bagasse pellets and crumble solidify aqueous waste at up to 5× their weight (vs ~2.5:1 wood), up to about half the sorbent mass per volume solidified, so less saturated tonnage leaves the gate each cycle, with a renewable material and documentation for compliance.",
    useCases:["Leachate solidification","Aqueous waste streams","Pond & pit handling","Storm & overflow events"],
    proof:["Up to 5:1 absorption","Renewable, low-dust","SDS + spec","Bulk supply"],
    procurement:["Pilot for the budget cycle","RFP-ready documentation kit","Bulk / truckload","Freight-aware pricing"],
    faq:[
      { q:"Can we run a pilot?", a:"Yes, we'll scope a pilot aligned to your budget cycle and provide an RFP-ready documentation kit (spec, SDS, certifications)." },
    ],
    form:"quote",
    products:["absorbent-pellets","absorbent-crumble"],
  },
  "distributors":{
    name:"Distributors & Resellers", icp:"Ag input distributors · farm co-ops",
    seo:{ title:"Biochar Distributor Pricing, Carbon-Negative Organic Line | American BioCarbon",
      desc:"Add an OMRI-listed, carbon-negative bagasse biochar line with a distributor margin model and stocking pilot. Get distributor pricing.",
      slug:"/industries/distributors", keyword:"biochar distributor",
      secondary:["biochar wholesale","organic biochar soil amendment","biochar soil amendment bulk"],
      schema:"Service + FAQPage" },
    h1:"A Differentiated Organic Line That Pulls Through",
    sub:"Add a carbon-negative, OMRI-listed bagasse biochar to your catalog, with a margin model, stocking pilot, and grower-facing proof.",
    primary:CTA.distributor, secondary:CTA.biochar, image:ASSETS.biocharLg,
    problem:"Commodity inputs are a margin race: when every distributor stocks the same SKU, price is your only lever and each competing quote drags your margin toward zero. You need a differentiated SKU with real demand drivers, water efficiency, organic, and a carbon story, plus support so it actually sells through.",
    fit:"OMRI-listed bagasse biochar with a USDA-ARS field study behind it, a distributor margin model, and a co-branded grower trial program to de-risk stocking.",
    useCases:["Organic / regenerative product line","Grower water-efficiency programs","Compost & blend inputs","Carbon-program participation"],
    proof:["OMRI · IBI certified","USDA-ARS field study","Margin model provided","Stocking pilot available"],
    procurement:["Distributor pricing & rebate tiers","Co-branded grower trial kit","Bulk & bulk-bag supply","No first-year exclusivity required"],
    faq:[
      { q:"How do you de-risk stocking?", a:"A stocking pilot plus a co-branded grower trial gives your reps a local proof point before you commit to volume." },
    ],
    form:"distributor",
    products:["agricultural-biochar","biochar-infused-soil"],
  },
  "soil-blenders":{
    name:"Soil Blenders & Compost", icp:"Soil/media blenders · commercial composters",
    seo:{ title:"Bagasse Biochar for Soil Blenders & Composters | American BioCarbon",
      desc:"Bagasse biochar that improves blend moisture performance and can shorten compost turnover time. Bulk supply. Request a sample or windrow trial.",
      slug:"/industries/soil-blenders", keyword:"compost biochar additive",
      secondary:["biochar for water retention","soil blend amendment","biochar bulk"],
      schema:"Service + FAQPage" },
    h1:"Faster Compost. Better Moisture in Your Blends.",
    sub:"For composters, the core problem is turnover time, every extra day a windrow sits is pad space that can't take a new batch. Research shows biochar can shorten compost cycles ~10 to 30% (validate in your own process), so you finish more batches per year on the same pad. For blenders, it firms up moisture performance in premium and sandy mixes.",
    primary:CTA.biochar, secondary:CTA.distributor, image:ASSETS.biocharLg,
    problem:"Compost turnover time caps how many batches you can finish per year, a fixed pad only holds so many windrows, so slower maturity directly cuts annual throughput and revenue per square foot. Blenders face moisture complaints in sandy and premium mixes and pressure to offer an organic/carbon story.",
    fit:"Peer-reviewed research shows biochar can shorten compost cycles ~10 to 30% (validate in your process) and raise pile temperature; in blends, bagasse biochar holds ~3 to 3.5× its weight in water. We support a side-by-side windrow or blend trial so you measure the effect yourself.",
    useCases:["Compost cycle acceleration","Windrow bulking & moisture","Premium blend water-holding","Organic / carbon-negative SKU"],
    proof:["Compost cycle-time research (validate in your process)","~3 to 3.5× water-holding in blends","OMRI · IBI certified","Bulk supply"],
    procurement:["Windrow / blend trial protocol","Bulk & bulk-bag supply","Freight-aware pricing","Spec + OMRI docs"],
    faq:[
      { q:"How do I prove the compost-speed benefit?", a:"Run a side-by-side windrow: biochar-amended vs control, same recipe and turning schedule, and measure days-to-maturity and peak temperature. We provide the trial protocol and data sheet." },
      { q:"What dose?", a:"Research commonly cites ~10% by volume as a starting point; we'll help you set a rate for your feedstock." },
    ],
    form:"biochar",
    products:["agricultural-biochar","biochar-infused-soil"],
  },
};

/* ============ FORMS ============ */
const FORMS = {
  sample:{
    name:"Request Industrial Sample Kit",
    h:"Request an Industrial Sample Kit",
    sub:"Your industrial sample is free, shipping and handling included. Tell us your use case and we'll ship it with the SDS and spec sheet. A specialist replies within one business day.",
    fields:[
      { n:"name", label:"Name", type:"text", req:true },
      { n:"company", label:"Company", type:"text", req:true },
      { n:"email", label:"Work email", type:"email", req:true },
      { n:"phone", label:"Phone", type:"tel", req:false },
      { n:"location", label:"Location (city / state)", type:"text", req:false },
      { n:"buyerType", label:"Buyer type", type:"select", req:false, options:["Oilfield services","Spill response","Environmental remediation","Industrial operations","Landfill / waste","Municipal / disaster","Other"], otherPh:"e.g. Marine terminal, Mining, Pipeline" },
      { n:"useCase", label:"Use case", type:"text", req:true, ph:"e.g. drilling-fluid solidification, spill cleanup, leachate" },
      { n:"current", label:"Current absorbent material", type:"text", req:false, ph:"e.g. wood pellets, clay" },
      { n:"volume", label:"Estimated tonnage per month", type:"number", req:false, ph:"e.g. 20 (tons)" },
      { n:"format", label:"Format needed", type:"select", req:false, options:["Pellets","Crumble","Bulk","1 MT bulk bag","Not sure"] },
      { n:"timeline", label:"Timeline", type:"select", req:false, options:["Active need now","This quarter","Evaluating","Just researching"] },
      { n:"request", label:"Request type", type:"select", req:true, options:["Sample kit","Sample + bulk quote","Spec sheet / SDS","Talk to a specialist"] },
    ],
    confirm:"Thanks, your free sample request is in (shipping and handling included). A remediation specialist will reply within one business day with the SDS and spec sheet attached.",
    autoreply:"Subject: Your American BioCarbon sample kit\n\nThanks for requesting a sample kit. Attached are the SDS and spec sheet for our bagasse absorbent. A specialist will follow up within one business day to confirm your use case, volume, and ship-to., American BioCarbon, White Castle, LA",
    routing:"Industrial → remediation specialist queue. Create Account + Contact + Deal (type: Sample) + Sample Request; auto-attach SDS/spec.",
    scoring:"+ truckload volume, + zone A/B, + active-now timeline, + named use case; − personal email, − 'just researching'.",
  },
  quote:{
    name:"Get Bulk Absorbent Quote",
    h:"Get a Bulk Absorbent Quote",
    sub:"Give us your volume and location for freight-aware pricing. SDS and spec included with your quote.",
    fields:[
      { n:"name", label:"Name", type:"text", req:true },
      { n:"company", label:"Company", type:"text", req:true },
      { n:"email", label:"Work email", type:"email", req:true },
      { n:"phone", label:"Phone", type:"tel", req:false },
      { n:"product", label:"Product", type:"select", req:true, options:["Absorbent Pellets","100% Biochar","BioSoil","Absorbent Crumble","Multipurpose Fiber","Multiple / not sure"] },
      { n:"request", label:"Request type", type:"select", req:false, options:["Bulk quote","Spec sheet / SDS","Sample first","Talk to specialist"] },
      { n:"location", label:"Ship-to (city / state)", type:"text", req:true },
      { n:"format", label:"Format", type:"select", req:false, options:["Bulk","1 MT bulk bag","20/40 lb bags","Truckload","Not sure"] },
      { n:"volume", label:"Estimated volume & frequency", type:"text", req:true, ph:"e.g. 2 truckloads / month" },
      { n:"useCase", label:"Use case", type:"text", req:false },
      { n:"timeline", label:"Timeline", type:"select", req:false, options:["Active need now","This quarter","Evaluating"] },
    ],
    confirm:"Thanks, your bulk quote request is in. We'll reply within one business day with freight-aware pricing plus the SDS and spec sheet.",
    autoreply:"Subject: Your American BioCarbon bulk quote\n\nThanks for your quote request. We're preparing freight-aware pricing for your volume and ship-to. Meanwhile, the SDS and spec sheet are attached., American BioCarbon",
    routing:"Create Account + Contact + Deal (type: Bulk / Truckload); assign to sales; freight-zone the ship-to.",
    scoring:"+ volume tier, + recurring frequency, + zone A/B, + active-now.",
  },
  biochar:{
    name:"Request Biochar Sample",
    h:"Request a Biochar Sample",
    sub:"Your biochar sample is free, shipping and handling included. For growers, blenders, composters, and distributors. Tell us your use and we'll send it with the spec sheet and its ~3 to 3.5× water-holding figure (per our technical report).",
    fields:[
      { n:"name", label:"Name", type:"text", req:true },
      { n:"company", label:"Company / farm", type:"text", req:true },
      { n:"email", label:"Email", type:"email", req:true },
      { n:"phone", label:"Phone", type:"tel", req:false },
      { n:"buyerType", label:"You are a", type:"select", req:true, options:["Distributor / co-op","Soil blender","Composter","Grower","Landscape / nursery","Other"], otherPh:"e.g. Golf course, Vineyard, Greenhouse" },
      { n:"useCase", label:"Intended use", type:"text", req:true, ph:"e.g. compost trial, blend, field trial" },
      { n:"volume", label:"Estimated volume", type:"text", req:false },
      { n:"resale", label:"Resale or own use", type:"select", req:false, options:["Resale","Own use","Both"] },
      { n:"certs", label:"Certifications needed", type:"text", req:false, ph:"e.g. OMRI" },
    ],
    confirm:"Thanks, your free biochar sample request is in (shipping and handling included). We'll follow up within one business day with the sample, spec sheet, and (for composters) a side-by-side windrow trial protocol.",
    autoreply:"Subject: Your American BioCarbon biochar sample\n\nThanks for your interest. The spec sheet is attached; we'll confirm your sample and ship-to shortly. Composters: ask about our side-by-side windrow trial protocol., American BioCarbon",
    routing:"Create Account + Contact + Deal (type: Sample, segment: ag); route to distributor/ag lead.",
    scoring:"+ distributor/blender/composter, + resale, + volume; − consumer/home use.",
  },
  distributor:{
    name:"Get Distributor Pricing",
    h:"Get Distributor Pricing",
    sub:"Add a carbon-negative biochar line without over-committing inventory, we send the margin model and a low-volume stocking pilot.",
    fields:[
      { n:"name", label:"Name", type:"text", req:true },
      { n:"company", label:"Company", type:"text", req:true },
      { n:"email", label:"Work email", type:"email", req:true },
      { n:"phone", label:"Phone", type:"tel", req:false },
      { n:"companyType", label:"Company type", type:"select", req:true, options:["Ag input distributor","Farm co-op","Soil blender","Landscape supply","Other"], otherPh:"e.g. Garden center chain, Hydroponics retailer" },
      { n:"geography", label:"Geography served", type:"text", req:true },
      { n:"volume", label:"Estimated annual volume", type:"text", req:false },
      { n:"packaging", label:"Packaging needs", type:"select", req:false, options:["Bulk","1 MT bulk bag","Bagged retail","Mixed"] },
    ],
    confirm:"Thanks, we'll send the distributor margin model and stocking-pilot options within one business day.",
    autoreply:"Subject: American BioCarbon distributor program\n\nThanks for your interest in carrying our line. We're preparing the margin model and stocking-pilot details for your geography., American BioCarbon",
    routing:"Create Account + Distributor Agreement (draft) + Deal; route to founder/distributor lead.",
    scoring:"+ multi-branch, + organic demand region, + volume; − national-exclusivity-first.",
  },
  carbon:{
    name:"Request Carbon Removal Info",
    h:"Request Carbon Removal Information",
    sub:"Durable, deployment-backed CORCs via Puro.earth. Tell us your program and we'll share current data and forward-purchase options.",
    fields:[
      { n:"name", label:"Name", type:"text", req:true },
      { n:"company", label:"Company", type:"text", req:true },
      { n:"email", label:"Work email", type:"email", req:true },
      { n:"buyerType", label:"Buyer type", type:"select", req:true, options:["Corporate / ESG","Carbon broker","Marketplace","Project developer","Other"], otherPh:"e.g. Airline, Tech company, Investment fund" },
      { n:"annual", label:"Annual CDR interest (tCO₂e)", type:"text", req:false },
      { n:"timeline", label:"Timeline", type:"select", req:false, options:["This year","Next 12 months","Exploring"] },
      { n:"registry", label:"Registry / standard requirements", type:"text", req:false, ph:"e.g. Puro.earth" },
      { n:"procurement", label:"Procurement process notes", type:"textarea", req:false },
    ],
    confirm:"Thanks, we'll follow up with current carbon-removal data and forward-purchase options tied to our deployment pipeline.",
    autoreply:"Subject: American BioCarbon carbon removal\n\nThanks for your interest in durable, deployment-backed carbon removal. We'll share current methodology data and forward-purchase options aligned to our deployment pipeline., American BioCarbon",
    routing:"Create Account + Deal (type: CDR); route to founder/carbon lead; link to deployment forecast.",
    scoring:"+ annual volume, + this-year timeline, + Puro/standard match; − credits-without-deployment expectation.",
  },
  docs:{
    name:"Request Technical Documentation",
    h:"Request Spec Sheets, SDS &amp; Technical Data",
    sub:"Tell us where to send it and we'll email the documents relevant to your application, spec sheets, SDS, lab analyses, certificates, and our research package.",
    fields:[
      { n:"name", label:"Name", type:"text", req:true },
      { n:"company", label:"Company", type:"text", req:true },
      { n:"email", label:"Work email", type:"email", req:true },
      { n:"phone", label:"Phone", type:"tel", req:false },
      { n:"role", label:"Your role", type:"select", req:true, options:["Procurement / Purchasing","Operations","EHS / Safety","Environmental / Remediation","Agronomy / Technical","Sustainability / Carbon","Distribution / Resale","Other"], otherPh:"e.g. R&D, Consultant, Facilities" },
      { n:"industry", label:"Industry / application", type:"select", req:true, options:["Oil & gas","Spill response","Environmental remediation","Industrial operations","Landfill / leachate","Municipal / disaster","Agriculture / distribution","Soil blending / compost","Carbon / ESG","Other"], otherPh:"e.g. Marine, Mining, Pipeline" },
      { n:"documents", label:"Which documents?", type:"select", req:true, options:["Absorbent spec sheet","Absorbent SDS","Absorbent spec + SDS","Biochar spec + lab analysis","OMRI / IBI / Puro certificates","Peer-reviewed research package","All technical documents"] },
      { n:"useCase", label:"Use case (helps us send the right data)", type:"text", req:false },
    ],
    confirm:"Thanks, check your inbox. We've routed the requested documents to your email and a specialist will follow up if a spec or SDS needs tailoring to your application.",
    autoreply:"Subject: Your American BioCarbon technical documents\n\nThanks for your request. Attached are the spec sheets, SDS, and/or lab data for your application. Our full peer-reviewed research package is included where requested. A specialist will follow up within one business day., American BioCarbon, White Castle, LA",
    routing:"Gated download. Create Contact + Activity (doc request) + Deal if volume signal; tag by role + industry + documents; deliver files by email.",
    scoring:"+ procurement/EHS role, + oil&gas/remediation industry, + 'all documents', + named use case; − personal email, − student/research-only.",
  },
  contact:{
    name:"Talk to a Specialist",
    h:"Talk to a Remediation Specialist",
    sub:"Tell us what you're solving. We'll reply within one business day with the right documentation and next step.",
    fields:[
      { n:"name", label:"Name", type:"text", req:true },
      { n:"company", label:"Company", type:"text", req:true },
      { n:"email", label:"Work email", type:"email", req:true },
      { n:"phone", label:"Phone", type:"tel", req:false },
      { n:"topic", label:"What do you need?", type:"select", req:true, options:["Industrial absorbent","Agriculture / biochar","Distributor program","Carbon removal","Something else"], otherPh:"e.g. Partnership, Media, Co-location" },
      { n:"message", label:"Message", type:"textarea", req:false },
    ],
    confirm:"Thanks, a specialist will reply within one business day.",
    autoreply:"Subject: We got your message, American BioCarbon\n\nThanks for reaching out. A specialist will reply within one business day with the right documentation and next step., American BioCarbon, White Castle, LA",
    routing:"Route by topic to the matching queue; create Contact + Activity + follow-up task.",
    scoring:"By topic + volume signals in message.",
  },
};

/* ============ DEEP INDUSTRY PAGES ============ */

const ENV_REMEDIATION = {
  seo:{ title:"Environmental Remediation Absorbent | Soil & Groundwater Cleanup | American BioCarbon",
    desc:"Engineered for brownfield remediation, soil cleanup, and contaminated groundwater. 5:1 absorption, predictable retention under landfill pressure, natural biodegradation.",
    slug:"/environmental-remediation-solutions", keyword:"environmental remediation absorbent" },
  h1:"Remediation Made Efficient",
  sub:"For site managers who own the cost of containment and disposal",
  primary:CTA.specialist, secondary:CTA.quote,
  painPoints:[
    { title:"Site Containment Costs", desc:"Holding saturated material on-site ties up pad space and cash flow. Lower absorption rates force you to deploy 2–3× more volume per job." },
    { title:"Disposal Tonnage Billing", desc:"Waste disposal is charged by the ton. Lower-capacity sorbents mean heavier saturated loads and higher bills per cubic yard of remediated soil." },
    { title:"Regulatory & ESG Exposure", desc:"Persistent synthetic polymers in landfill streams invite scrutiny. Your clients and regulators want genuine waste reduction and natural degradation." },
    { title:"Supply Chain Friction", desc:"Last-minute shortages or quality variance from commodity suppliers derail project timelines and inflate emergency logistics costs." }
  ],
  whyABC:[
    { title:"5:1 absorption = 2.5× less tonnage", desc:"Fewer bags per job. Less saturated weight to disposal. Direct cost savings on every project." },
    { title:"Holds under landfill overburden", desc:"The honeycomb microstructure is stable even under pressure. No re-release. No compliance callbacks." },
    { title:"100% natural biodegradation", desc:"Bagasse breaks down on schedule. No persistent polymers. No long-term leachate risk." },
    { title:"Predictable supply", desc:"We commit to delivery windows. No stockouts. No timeline slippage." }
  ],
  applications:["Dredged-sediment dewatering","Slurry-wall & trench-spoil management","Hydrocarbon-impacted soil","Brownfield & frac-out response","Groundwater remediation","Landfill leachate handling"],
  caseStudy:{
    scenario:"2-acre brownfield with soil contamination and dewatering need.",
    previous:"Standard absorbent: 18 truck deliveries, 120 tons saturated waste.",
    result:"American BioCarbon 5:1: 7 trucks, 48 tons saturated waste. Saved: 11 loads of logistics, 72 tons of disposal billing, zero compliance callbacks."
  },
  procurement:[
    { step:"01", label:"Site scoping", desc:"Share your contamination profile. We confirm fit and send spec with field-proven data." },
    { step:"02", label:"Pilot test", desc:"Stage a super-sack on-site. Your team validates absorption, retention, and cleanup benefit." },
    { step:"03", label:"Committed delivery", desc:"Once approved, we schedule delivery to YOUR timeline. No delays." },
    { step:"04", label:"Full support", desc:"Our team available through project close for logistics, troubleshooting, or scope adjustments." }
  ],
};

const RESELLERS_INDUSTRIES = {
  seo:{ title:"Distributor & Reseller Program | Industrial Absorbent | American BioCarbon",
    desc:"Add a renewable, high-margin absorbent line. Tiered pricing, co-branded programs, dedicated account management, and predictable supply.",
    slug:"/distributors-resellers-industries", keyword:"industrial absorbent distributor program" },
  h1:"A Better Margin. A Differentiated Story.",
  sub:"For industrial distributors and consolidated service providers",
  primary:CTA.distributor, secondary:CTA.quote,
  painPoints:[
    { title:"Commodity Margin Collapse", desc:"Every catalog carries the same wood pellets and clay. Price is the only lever. Your margin compresses to unsustainable levels." },
    { title:"Inventory Risk", desc:"Slow-moving SKUs of undifferentiated products tie up working capital. Customers shop on price, loyalty disappears at the next RFQ." },
    { title:"Weak Competitive Position", desc:"Without a unique product or story, you're interchangeable. Customers pit you against online retailers on price alone." },
    { title:"Support Burden", desc:"You're on the hook for technical questions on products you didn't develop, with no manufacturer backing." }
  ],
  whyABC:[
    { title:"Premium tiers & margins", desc:"Our distributor program offers volume-based tiering that rewards growth. Real margin room for your business." },
    { title:"Differentiated product", desc:"5:1 absorption, plant-based, carbon-negative story. Customers have a reason to buy—and stick." },
    { title:"We handle tech support", desc:"Spec sheets, field trials, and technical questions—we're behind you so your team closes faster." },
    { title:"Predictable supply", desc:"No allocation games. Committed lead times. Your inventory planning is reliable." },
    { title:"Marketing co-op", desc:"Case studies, ROI models, sell-side tools. Your reps close faster with real proof." }
  ],
  program:[
    { title:"Tiered Margin Model", bullets:["Volume discounts that scale with growth","Quarterly rebates for hitting targets","No first-year exclusivity"] },
    { title:"Order Fulfillment", bullets:["48–72 hour turnaround","Dedicated logistics coordination","Real-time tracking"] },
    { title:"Sales Tools", bullets:["Co-branded case studies","Product docs for your reps","Joint webinars & content"] },
    { title:"Technical Support", bullets:["Direct access to our team","Field trial support","Application guidance"] },
    { title:"Communication", bullets:["Monthly forecasts","Real-time order status","Quarterly business reviews"] }
  ],
  getStarted:[
    { n:"01", t:"Consult", d:"Discuss territory, customers, sales goals. We model the margin opportunity and program structure." },
    { n:"02", t:"Pilot", d:"Start with a pilot order. Your team tests, gathers customer feedback. We provide everything you need." },
    { n:"03", t:"Ramp", d:"As volume grows, we assign a dedicated account manager, launch co-branded marketing, optimize supply." },
    { n:"04", t:"Grow", d:"Ongoing quarterly planning, monthly updates, proactive support." }
  ],
};

const RESELLERS_AGRICULTURE = {
  seo:{ title:"Biochar Distributor Program | Agriculture & Soil Blenders | American BioCarbon",
    desc:"Build your premium biochar line. OMRI-listed, proven field performance, grower support, and dedicated account management.",
    slug:"/distributors-resellers-agriculture", keyword:"biochar distributor agriculture" },
  h1:"Premium Biochar. Premium Margins. Premium Support.",
  sub:"For agricultural distributors, soil blenders, and input cooperatives",
  primary:CTA.distributor, secondary:CTA.biochar,
  painPoints:[
    { title:"Water & Nutrient Challenges", desc:"Growers in sandy and salt-affected soils struggle. Standard amendments don't move the needle on water retention or yield." },
    { title:"Commodity Input Pressure", desc:"Every input category compresses margins. Growers chase the cheapest option. Loyalty is transactional, not lasting." },
    { title:"ESG Demand", desc:"Growers increasingly want to demonstrate soil health and carbon stewardship. Commodity products don't tell that story." },
    { title:"Your Agronomic Gap", desc:"Recommending the right amendment requires knowledge. You need technical support, not more inventory risk." }
  ],
  whyABC:[
    { title:"OMRI-listed premium", desc:"Organic certification means certified growers and regenerative operations can use it immediately. Premium margin tier, instant." },
    { title:"Proven field performance", desc:"3–3.5× water holding with inherent N-P-K. Growers see real results, not just promises. That drives repeat purchases." },
    { title:"Unique value story", desc:"Carbon durability, honeycomb microstructure, inherent minerals. Growers have a reason to pay premium price and tell their peers." },
    { title:"Agronomic co-selling", desc:"We provide trial protocols, field study data, and direct education. Your reps sell with confidence and proof." },
    { title:"Scalable co-op", desc:"Joint marketing, demo kits, field trials that drive real volume—not just catalogs." }
  ],
  program:[
    { title:"Premium Margins", bullets:["Tiered pricing that rewards volume","Quarterly rebates for hitting targets","Co-op marketing budget"] },
    { title:"Grower Support", bullets:["Windrow & soil-trial protocols","Field study data vs. competitors","Comparison ROI calculators"] },
    { title:"Sales Enablement", bullets:["Co-branded case studies","Tech spec sheets","Certification docs"] },
    { title:"Reliable Supply", bullets:["Committed lead times","Flexible packaging","Seasonal forecasting"] },
    { title:"Direct Account Mgmt", bullets:["Dedicated account manager","Monthly reviews","Quarterly planning","Direct agronomic access"] }
  ],
  timeline:[
    { day:"Day 0", label:"Order confirmed", desc:"Payment terms set, material allocated." },
    { day:"Day 1–2", label:"Packaging & logistics", desc:"Material ready for staging. Logistics confirmed." },
    { day:"Day 3–5", label:"In transit", desc:"Real-time tracking link provided." },
    { day:"Day 5–7", label:"Delivery complete", desc:"Inspected. Follow-up on reorder timing." }
  ],
  communication:[
    { title:"Monthly Forecasts", desc:"Review your velocity, adjust inventory positioning so you never run short." },
    { title:"Order Tracking", desc:"Real-time status from production through delivery for you and your customers." },
    { title:"Grower Success Sharing", desc:"Field wins from your customers so your team has fresh proof to share with prospects." },
    { title:"Quarterly Reviews", desc:"Deep-dive on volumes, margins, strategy. Growth roadmap for both of us." },
    { title:"Escalation Line", desc:"Special orders, urgent shipments, or customer issues? Direct access to our ops team." }
  ],
  getStarted:[
    { n:"01", t:"Assessment", d:"Territory, customer profile, sales goals. We model market opportunity and margin." },
    { n:"02", t:"Pilot & education", d:"Stocking pilot + trial kits. Your reps and their growers see results." },
    { n:"03", t:"Ramp", d:"Dedicated account manager, co-branded marketing, optimized supply chain." },
    { n:"04", t:"Ongoing excellence", d:"Quarterly planning, monthly updates, proactive support." }
  ],
};

/* ============ CLAIM SAFETY TABLE ============ */
const CLAIMS = [
  { claim:"Absorption 5:1", safe:"Holds up to ~5× its weight in liquid (non-viscous), vs ~2.5× for typical wood pellets, per available product data", risky:"'Absorbs any chemical / any spill' or a hard 5:1 with no qualifier", proof:"Product spec / lab", page:"Home, Pellets, Crumble, industries", status:"lab-tested" },
  { claim:"Absorbency vs wood", safe:"Outperforms standard wood pellets (~2.5:1)", risky:"'Best absorbent on the market'", proof:"Product spec", page:"Compare, Pellets", status:"lab-tested" },
  { claim:"OMRI / IBI", safe:"OMRI Listed · IBI Certified", risky:"Implying broader approvals not held", proof:"Current listing IDs", page:"Proof band, Biochar, Technical", status:"verified" },
  { claim:"USDA Organic", safe:"USDA Organic pending", risky:"'USDA Organic certified'", proof:"USDA status", page:"Proof band, Biochar", status:"needs verification" },
  { claim:"Puro.earth", safe:"Puro.earth certified carbon removal (CORCs)", risky:"Fixed $/ton or tCO₂e without confirmation", proof:"Puro certification + MRV", page:"Carbon Removal", status:"verified" },
  { claim:"Heavy metals", safe:"Well below IBI / EPA Class A thresholds (per lab analyses)", risky:"'Zero contaminants / completely pure'", proof:"Independent lab reports", page:"Technical, Biochar", status:"lab-tested" },
  { claim:"Water-holding", safe:"Holds ~3 to 3.5× its weight in water (per technical report)", risky:"'Holds 5× water' as a blanket claim", proof:"ProGreaux technical report", page:"Biochar, Soil, Ag section", status:"lab-tested" },
  { claim:"Carbon durability", safe:"H/C molar ratio <0.7 supports durable, long-term carbon storage", risky:"'Permanent forever' with no standard", proof:"Lab H/C + Puro methodology", page:"Carbon, Technical", status:"lab-tested" },
  { claim:"Compost speed", safe:"Research shows biochar can shorten compost cycles ~10 to 30%; validate in your own process", risky:"'Our biochar cuts 14 days off your compost'", proof:"Peer-reviewed (general) + client's own trial", page:"Soil Blenders, Biochar", status:"field-supported" },
  { claim:"USDA-ARS study", safe:"Backed by a multi-year USDA-ARS field study on sugarcane bagasse biochar", risky:"Overstating specific yield outcomes", proof:"Study citation", page:"Biochar, About", status:"field-supported" },
  { claim:"Animal feed/health", safe:"(Not used), bedding absorbency only if added", risky:"Any feed or animal-health benefit", proof:"AFIA/AAFCO/GRAS review", page:"None (excluded)", status:"needs verification" },
  { claim:"Carbon $/ton", safe:"Shared during diligence, methodology-specific", risky:"Public fixed price/ton or tCO₂e per ton", proof:"Puro methodology + verified data", page:"Carbon (diligence only)", status:"needs verification" },
];
