#!/usr/bin/env node
/**
 * Copy the nurture plan into the Sales OS.
 *
 * The plan is written and edited as markdown in the outer repo
 * (sales-department/campaigns/NURTURE-PLAN.md) because that is where Victor and Daniel
 * fill in the copy slots. The Sales OS shows the same document under Execute > Nurture
 * Plan so nobody has to open GitHub to read it. This script is the only bridge: it reads
 * the markdown and writes sales/nurture-data.js. The generated file is committed, so the
 * website repo still builds on a machine that does not have the outer repo checked out.
 *
 * Run by hand after editing the plan, then deploy the Sales OS:
 *   node scripts/build-nurture.mjs && ./scripts/deploy-sales-os.sh
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "..", "sales-department", "campaigns", "NURTURE-PLAN.md");
const OUT = join(ROOT, "sales", "nurture-data.js");

if (!existsSync(SRC)) {
  console.log(`build-nurture: ${SRC} not present, keeping the committed nurture-data.js`);
  process.exit(0);
}
const md = readFileSync(SRC, "utf8");
const body = md.replace(/^---[\s\S]*?---\s*/, ""); // drop the frontmatter block
const stamp = new Date().toISOString().slice(0, 10);
writeFileSync(
  OUT,
  `/* GENERATED by scripts/build-nurture.mjs from sales-department/campaigns/NURTURE-PLAN.md on ${stamp}.\n` +
    `   Edit the markdown, not this file. */\n` +
    `window.NURTURE_MD = ${JSON.stringify(body)};\n` +
    `window.NURTURE_STAMP = ${JSON.stringify(stamp)};\n`
);
console.log(`✓ nurture-data.js: ${body.length} chars from NURTURE-PLAN.md`);
