#!/usr/bin/env node
/**
 * Copy the nurture plan into the Sales OS.
 *
 * The plan is written and edited as markdown in the outer repo
 * (sales-department/campaigns/NURTURE-PLAN.md) because that is where Victor and Daniel
 * fill in the copy slots. The Sales OS shows the same document under Execute > Nurture
 * Plan so nobody has to open GitHub to read it. This script is the only bridge: it reads
 * the markdown and writes sales/nurture-data.js. The generated file is committed, so the
 * website repo still builds on a machine that does not have the outer repo checked out.
 *
 * Run by hand after editing the plan, then deploy the Sales OS:
 *   node scripts/build-nurture.mjs && ./scripts/deploy-sales-os.sh
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(ROOT, "..", "sales-department", "campaigns", "NURTURE-PLAN.md");
const OUT = join(ROOT, "sales", "nurture-data.js");

if (!existsSync(SRC)) {
  console.log(`build-nurture: ${SRC} not present, keeping the committed nurture-data.js`);
  process.exit(0);
}
const md = readFileSync(SRC, "utf8");
const body = md.replace(/^---[\s\S]*?---\s*/, ""); // drop the frontmatter block
const stamp = new Date().toISOString().slice(0, 10);
writeFileSync(
  OUT,
  `/* GENERATED by scripts/build-nurture.mjs from sales-department/campaigns/NURTURE-PLAN.md on ${stamp}.\n` +
    `   Edit the markdown, not this file. */\n` +
    `window.NURTURE_MD = ${JSON.stringify(body)};\n` +
    `window.NURTURE_STAMP = ${JSON.stringify(stamp)};\n`
);
console.log(`✓ nurture-data.js: ${body.length} chars from NURTURE-PLAN.md`);

/* Second output: the email template module, made into a browser global so the Sales OS can
   render a nurture email exactly the way the Pages Function will send it. _email.js is an ES
   module with `export` keywords and no imports, so the transform is: strip `export `, wrap in
   an IIFE, hand the public names to window.EMAIL_TPL. If _email.js ever grows an import this
   will break loudly at load, which is the right failure. */
const tplSrc = readFileSync(join(ROOT, "functions", "api", "_email.js"), "utf8");
if (/^\s*import\s/m.test(tplSrc)) throw new Error("_email.js has an import; build-nurture cannot bundle it");
const stripped = tplSrc.replace(/^export\s+(const|function|let)\s/gm, "$1 ");
const NAMES = ["esc", "origin", "SPEC", "STYLES", "renderEmail", "SEQUENCES", "buildAutoreply", "buildInternalLead", "buildNurtureEmail", "_internals"];
for (const n of NAMES) if (!new RegExp(`(const|function)\\s+${n}\\b`).test(stripped)) throw new Error(`_email.js no longer defines ${n}`);
writeFileSync(
  join(ROOT, "sales", "email-template.js"),
  `/* GENERATED by scripts/build-nurture.mjs from functions/api/_email.js on ${stamp}. Edit the source. */\n` +
    `(function(){\n${stripped}\nwindow.EMAIL_TPL = { ${NAMES.join(", ")} };\n})();\n`
);
console.log(`✓ email-template.js: bundled _email.js for the browser`);
